### ISSUE TITLE
PTRArchiveQuery 已经不可用

### ISSUE THREAD

**Issue by 1c3z** [shmilylty/OneForAll#10]
http://ptrarchive.com/tools/search3.htm  
访问404

**Comment by shmilylty** [comment]
谢谢反馈，ptrarchive.com的地址改为了http://ptrarchive.com/tools/search4.htm，
代码已经做了[修改](https://github.com/shmilylty/OneForAll/commit/da4e3bbd2ab0e4e0759be9163f1416b338249c77)。
