### ISSUE TITLE
(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')),)

### ISSUE THREAD

**Issue by xxsmile123** [shmilylty/OneForAll#100]
我的环境是ubantu 1804、python 3.8.3，使用了oneforall的最新的代码。但是还是出现以下三种错误：
![image](https://user-images.githubusercontent.com/43473886/83110250-5b744680-a0f5-11ea-9f2a-52d3a3496280.png)
包含两个错误
![image](https://user-images.githubusercontent.com/43473886/83110308-73e46100-a0f5-11ea-8d39-ee93aa819998.png)
包含一个错误

**Comment by shmilylty** [comment]
第二张图中的错误是因为你没有配置代理，导致不能访问一些被墙的网站。

**Comment by xxsmile123** [comment]
那第一张图呢？老哥

**Comment by shmilylty** [comment]
> 那第一张图呢？老哥

这个可能是请求时出现的网络链接问题，暂时没有解决方法，目前来说不影响整体的收集工作。
