### ISSUE TITLE
OSError:[WinError 10038]

### ISSUE THREAD

**Issue by Corgizz** [shmilylty/OneForAll#104]
![图片](https://user-images.githubusercontent.com/33239583/84001573-7ec2af80-a999-11ea-940e-b0daa6ac6df3.png)

**Comment by shmilylty** [comment]
这个可能是Python自身的问题，一时半会儿解决不了。

**Comment by shmilylty** [comment]
这个可能是Python自身的问题，一时半会儿解决不了。
