### ISSUE TITLE
('Detected the new Cloudflare challenge.',) 和 ('value',)

### ISSUE THREAD

**Issue by Corgizz** [shmilylty/OneForAll#108]
Centos 7.5 
python 3.8.3
![图片](https://user-images.githubusercontent.com/33239583/85383131-34812700-b572-11ea-8faf-89d5875daa60.png)

**Comment by shmilylty** [comment]
> ('Detected the new Cloudflare challenge.',)
出现这个报错的原因是 bufferover开启了Cloudflare的浏览器验证，为了绕过这一验证OneForAll使用了一个cloudscraper库，但是Cloudflare的验证一直再变，所以导致有时候不能绕过验证验证，可以尝试更新一下cloudscraper库再跑看看。
