### ISSUE TITLE
Running massdns to brute subdomains

### ISSUE THREAD

**Issue by websecer** [shmilylty/OneForAll#109]
这一步太占用网速了，百度都打不开了，有什么办法可以缓解下吗？

**Comment by shmilylty** [comment]
可以在setting.py里https://github.com/shmilylty/OneForAll/blob/master/config/setting.py#L48将brute_concurrent_num爆破并发数设置为更小的数。

**Comment by attacker007** [comment]
Hi @shmilylty i think you are using massdns default number of threads. Can you please increase number of threads to like 10000 at least... Or add that option of threads so that user can modify in settings? 


Thanks !

**Comment by shmilylty** [comment]
> Hi @shmilylty i think you are using massdns default number of threads. Can you please increase number of threads to like 10000 at least... Or add that option of threads so that user can modify in settings?
> 
> Thanks !

https://github.com/shmilylty/OneForAll/blob/master/config/setting.py#L40
