### ISSUE TITLE
Windows报错

### ISSUE THREAD

**Issue by yizhicaiji123** [shmilylty/OneForAll#110]
python3.8    代理已经设置好了
![image](https://user-images.githubusercontent.com/51145610/86505350-ee3f8980-bdf5-11ea-855e-ed30e340dfd0.png)
![image](https://user-images.githubusercontent.com/51145610/86505340-cfd98e00-bdf5-11ea-9cf8-94e3780bb091.png)

**Comment by shmilylty** [comment]
检查一下代理是否可用
