### ISSUE TITLE
cannot import name 'utils' from 'common'

### ISSUE THREAD

**Issue by p865** [shmilylty/OneForAll#111]
**i have used pip to install utils:**
pip install python-utils
Collecting python-utils
  Downloading python_utils-2.4.0-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: six in c:\users\fengj\appdata\roaming\python\python38\site-packages (from python-utils) (1.15.0)
Installing collected packages: python-utils
Successfully installed python-utils-2.4.0 
**but it still not work**              

Traceback (most recent call last):
  File "oneforall.py", line 15, in <module>
    import dbexport
  File "D:\Python Project\OneForAll-master\dbexport.py", line 13, in <module>
    from common import utils
ImportError: cannot import name 'utils' from 'common'

**Comment by shmilylty** [comment]
What is your run command？

**Comment by shmilylty** [comment]
You do need to install python-utils lib，because utils is OneForAll file https://github.com/shmilylty/OneForAll/blob/master/common/utils.py

**Comment by p865** [comment]
> You do need to install python-utils lib，because utils is OneForAll file https://github.com/shmilylty/OneForAll/blob/master/common/utils.py

my bad,i thought it's my lib mistake,thanks a lot~
