### ISSUE TITLE
Cannot allocate memory failure

### ISSUE THREAD

**Issue by uBadRequest** [shmilylty/OneForAll#113]
**Describe the bug**
Cannot allocate memory

**To Reproduce**
1. Enumerate subdomains for 500 root domains.
2. 5th domain causes error when it runs massdns, cannot allocate memory.

**Expected behavior**
To run without crashing

**Screenshots**
![image](https://user-images.githubusercontent.com/47282747/87225701-eedba100-c35c-11ea-88c8-9fed5811a896.png)

**Desktop (please complete the following information):**
 - OS: [Debian 10] 8GB of ram
 - Python 3.7

**Additional context**
Can you add a flag that just grabs the subdomains from all the domains and don't do any massdns or port scanning?

**Comment by shmilylty** [comment]
Please try to re-clone and test it with the latest code. if you have any questions, please explain in detail.
