### ISSUE TITLE
Add WebAnalyze

### ISSUE THREAD

**Issue by uBadRequest** [shmilylty/OneForAll#114]
**Is your feature request related to a problem? Please describe.**
After finding all subdomains, I want to know details about whats running on those subdomains.

**Describe the solution you'd like**
Run WebAnalyze and output to sqlite database, I would have this run weekly so only update if there has been changes.

**Describe alternatives you've considered**
Manually running running webanalyze afterwards.

**Comment by shmilylty** [comment]
Currently, the fingerprint identification module is being optimized.
