### ISSUE TITLE
优化dbexport后生成不了结果了

### ISSUE THREAD

**Issue by jhhd88** [shmilylty/OneForAll#115]
**是否使用了最新代码**
是

**Bug描述**
优化dbexport后生成不了结果了

**运行环境**
 - Windows 10 x64
 - Python版本：3.8
 - OneForAll版本：最新
 
**如何复现**
复现步骤（选写）

复现命令（必写）

**报错文本**
复制完整的报错文本（必写）

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
![image](https://user-images.githubusercontent.com/15847202/87242068-f33ab380-c45b-11ea-971a-54ddc1a4f4cf.png)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**Comment by JrDw0** [comment]
dbexport模块输入从直接输入表名改为输入域名或者域名文件即可（与主文件相同的输入形式），输入的是否符合？

**Comment by JrDw0** [comment]
ccb105b87b3d13e51ba6ab6df5554ed3d81a77b0
已修复 可以拉取最新代码测试一下

**Comment by jhhd88** [comment]
> [ccb105b](https://github.com/shmilylty/OneForAll/commit/ccb105b87b3d13e51ba6ab6df5554ed3d81a77b0)
> 已修复 可以拉取最新代码测试一下

已解决
