### ISSUE TITLE
No such file cdn_cname_keywords.json

### ISSUE THREAD

**Issue by an0n7m** [shmilylty/OneForAll#118]
**是否使用了最新代码**
是

**Bug描述**
新添加的判断CDN模块代码中需要cdn_cname_keywords.json，项目中没有该文件

**运行环境**
 - 系统：[Ubuntu 20.04 x64]（必写）
 - Python版本：[3.8.2]（必写）
 - OneForAll版本：[最新]（必写）
 
**如何复现**
复现步骤（选写）

复现命令（必写）
python3 oneforall.py --target example.com run
**报错文本**
复制完整的报错文本（必写）
Traceback (most recent call last):
  File "oneforall.py", line 21, in <module>
    from modules import iscdn
  File "/home/user/Documents/OneForAll/modules/iscdn.py", line 15, in <module>
    cdn_cname_keyword = utils.load_json(data_dir.joinpath('cdn_cname_keywords.json'))
  File "/home/user/Documents/OneForAll/common/utils.py", line 220, in load_json
    with open(path) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Documents/OneForAll/data/cdn_cname_keywords.json'

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**Comment by shmilylty** [comment]
已解决
