### ISSUE TITLE
CookieError: Illegal key

### ISSUE THREAD

**Issue by jhhd88** [shmilylty/OneForAll#121]
**是否使用了最新代码**
是

**Bug描述**
跑一个域名到了最后的 Identify module的时候，就出现CookieError: Illegal key

**运行环境**
 - 系统：Windows 10 x64
 - Python版本：3.8
 - OneForAll版本：最新
 
**如何复现**
复现步骤（选写）

复现命令（必写）

**报错文本**
复制完整的报错文本（必写）

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
![image](https://user-images.githubusercontent.com/15847202/88789874-dd522000-d1c9-11ea-9465-79f74e526fb4.png)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**Comment by shmilylty** [comment]
这个模块暂时不稳定，请后续优化稳定后再使用。
