### ISSUE TITLE
期待OneForAll增加个支持python module方式引入

### ISSUE THREAD

**Issue by dean2021** [shmilylty/OneForAll#123]
期待oneforall增加个支持module方式引入功能，类似这种：

```python
import sublist3r 
subdomains = sublist3r.main(domain, no_threads, savefile, ports, silent, verbose, enable_bruteforce, engines)
```
这样就可以愉快的把OneForAll整合到其它项目中里了，不用每次都要修改OneForAll的源码了

**Comment by shmilylty** [comment]
参考test.py

**Comment by dean2021** [comment]
> 参考test.py

参考了，会报 AttributeError: module 'dbexport' has no attribute 'export'

**Comment by shmilylty** [comment]
> 参考了，会报 AttributeError: module 'dbexport' has no attribute 'export'

你的代码是怎么写的？

**Comment by dean2021** [comment]
> > 参考了，会报 AttributeError: module 'dbexport' has no attribute 'export'
> 
> 你的代码是怎么写的？

OneForAll放到extension目录下了

```python

import os
import sys

BASE_DIR = os.path.abspath(os.path.join(os.path.abspath(__file__), '../core', 'extension'))
ONE_FOR_ALL_DIR = os.path.abspath(os.path.join(BASE_DIR, 'OneForAll'))
sys.path.extend([ONE_FOR_ALL_DIR])
from core.extension.OneForAll.oneforall import OneForAll

if __name__ == '__main__':
    test = OneForAll(target='qq.com')
    test.brute = False
    test.req = False
    test.dns = False
    test.takeover = False
    test.format = "json"
    test.run()
    result = test.datas
    print(result)


```

**Comment by shmilylty** [comment]
> > > 参考了，会报 AttributeError: module 'dbexport' has no attribute 'export'
> > 
> > 
> > 你的代码是怎么写的？
> 
> OneForAll放到extension目录下了
> 
> ```python
> import os
> import sys
> 
> BASE_DIR = os.path.abspath(os.path.join(os.path.abspath(__file__), '../core', 'extension'))
> ONE_FOR_ALL_DIR = os.path.abspath(os.path.join(BASE_DIR, 'OneForAll'))
> sys.path.extend([ONE_FOR_ALL_DIR])
> from core.extension.OneForAll.oneforall import OneForAll
> 
> if __name__ == '__main__':
>     test = OneForAll(target='qq.com')
>     test.brute = False
>     test.req = False
>     test.dns = False
>     test.takeover = False
>     test.format = "json"
>     test.run()
>     result = test.datas
>     print(result)
> ```

你这个项目开源的吗，开源的话我可以调试一下，OneForAll正常使用是没有问题的，可能是导入问题。

**Comment by shmilylty** [comment]
或许可以参考一下#132
