### ISSUE TITLE
'NoneType' object has no attribute 'as_dict'

### ISSUE THREAD

**Issue by ggwshk** [shmilylty/OneForAll#124]
**是否使用了最新代码**
是

**Bug描述**
我试了几个操作系统了，都是报的这个错

**运行环境**
 - 系统：centos7.6、ubuntu16.04、windows2012
 - Python版本：3.8.0、3.8.3、3.8.5
 - OneForAll版本：最新版
 
**如何复现**
复现步骤（选写）
cd OneForAll/
python -m pip install -U pip setuptools wheel -i https://mirrors.aliyun.com/pypi/simple/
pip3 install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
python oneforall.py --target www.baidu.com run

复现命令（必写）
python oneforall.py --target www.baidu.com run

**报错文本**
复制完整的报错文本（必写）

AttributeError17:08:21,856:  ['NoneType' object has no attribute 'as_dict'
ERROR] database:40 - ('(sqlite3.OperationalError) no such table: www_baidu_com
',)
17:08:21,856 [ERROR] database:40 - ('(sqlite3.OperationalError) no such table: w
ww_baidu_com',)
17:08:21,856 [ERROR] database:40 - ('(sqlite3.OperationalError) no such table: w
ww_baidu_com',)
17:08:21,856 [ERROR] database:40 - ('(sqlite3.OperationalError) no such table: w
ww_baidu_com',)

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）
![image](https://user-images.githubusercontent.com/48978821/89881556-3cfff080-dbf8-11ea-963e-0da94161a5ad.png)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）
[oneforall.log](https://github.com/shmilylty/OneForAll/files/5056115/oneforall.log)

**其他补充**
关于bug的其他一些补充说明

**Comment by shmilylty** [comment]
> 复现命令（必写）
python oneforall.py --target www.baidu.com run

请使用主域名：
python oneforall.py --target baidu.com run
