### ISSUE TITLE
最终结果部分列空白

### ISSUE THREAD

**Issue by jhhd88** [shmilylty/OneForAll#125]
**是否使用了最新代码**
是

**Bug描述**
今天早上更新到最新版本，发现最终的csv结果文件里的部分子域存在cname,content,public空白，status显示200，本机ping域名也能解析出ip，已测试了10几个域名均如此。

**运行环境**
 - 系统：Windows 10 x64
 - Python版本：3.8
 - OneForAll版本：2020.8.13
 
**如何复现**
复现步骤（选写）

复现命令（必写）

**报错文本**
复制完整的报错文本（必写）

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
![image](https://user-images.githubusercontent.com/15847202/90092852-b31d6800-dd5c-11ea-9577-80224e40ac37.png)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by shmilylty** [comment]
复现命令是啥？

**Comment by jhhd88** [comment]
> 复现命令是啥？

oneforall.py --target xxx.com run

**Comment by jhhd88** [comment]
在今天更新之前都没有遇到过，今天更新了以后，所有的域名都是这种情况在，子域越多的出现的越多。

**Comment by shmilylty** [comment]
> > 复现命令是啥？
> 
> oneforall.py --target xxx.com run

具体目标是啥，方便告知吗，我好复现调试。

**Comment by jhhd88** [comment]
> > > 复现命令是啥？
> > 
> > 
> > oneforall.py --target xxx.com run
> 
> 具体目标是啥，方便告知吗，我好复现调试。

qq.com baidu.com 都有，并不是哪一个域名存在

**Comment by jhhd88** [comment]
> > > 复现命令是啥？
> > 
> > 
> > oneforall.py --target xxx.com run
> 
> 具体目标是啥，方便告知吗，我好复现调试。

我也用kali试过，也存在这问题。

**Comment by jhhd88** [comment]
还有一个很奇怪的问题，是从最开始用就存在的问题，WIN10 64系统，当遇到有泛解析的域名时，massdns进程的CPU占用率就达到100%，鼠标完全动不了，有些子域少的话，就可能等一段时间就恢复了，但有些子域多的时候，就会直接黑屏死机了。但我用kali虚拟机跑的时候就从来没发生过这种事，不管多大的子域都没出现过，CPU占用率都很低。所以现在我只能遇到一卡鼠标的域名就立即ctrl+c,然后把域名放到kali里去跑，但放到kali里又会出现结果里中文乱码的问题。

**Comment by shmilylty** [comment]
> 还有一个很奇怪的问题，是从最开始用就存在的问题，WIN10 64系统，当遇到有泛解析的域名时，massdns进程的CPU占用率就达到100%，鼠标完全动不了，有些子域少的话，就可能等一段时间就恢复了，但有些子域多的时候，就会直接黑屏死机了。但我用kali虚拟机跑的时候就从来没发生过这种事，不管多大的子域都没出现过，CPU占用率都很低。所以现在我只能遇到一卡鼠标的域名就立即ctrl+c,然后把域名放到kali里去跑，但放到kali里又会出现结果里中文乱码的问题。

现在最新的代码在kali跑也有乱码？

**Comment by jhhd88** [comment]
> > 还有一个很奇怪的问题，是从最开始用就存在的问题，WIN10 64系统，当遇到有泛解析的域名时，massdns进程的CPU占用率就达到100%，鼠标完全动不了，有些子域少的话，就可能等一段时间就恢复了，但有些子域多的时候，就会直接黑屏死机了。但我用kali虚拟机跑的时候就从来没发生过这种事，不管多大的子域都没出现过，CPU占用率都很低。所以现在我只能遇到一卡鼠标的域名就立即ctrl+c,然后把域名放到kali里去跑，但放到kali里又会出现结果里中文乱码的问题。
> 
> 现在最新的代码在kali跑也有乱码？

对，win没有乱码了。

刚刚又遇到一个问题
oneforall.py --target 17wo.cn run
![image](https://user-images.githubusercontent.com/15847202/90116719-7a938380-dd88-11ea-9899-2af84c4cffae.png)

**Comment by shmilylty** [comment]
> > > 还有一个很奇怪的问题，是从最开始用就存在的问题，WIN10 64系统，当遇到有泛解析的域名时，massdns进程的CPU占用率就达到100%，鼠标完全动不了，有些子域少的话，就可能等一段时间就恢复了，但有些子域多的时候，就会直接黑屏死机了。但我用kali虚拟机跑的时候就从来没发生过这种事，不管多大的子域都没出现过，CPU占用率都很低。所以现在我只能遇到一卡鼠标的域名就立即ctrl+c,然后把域名放到kali里去跑，但放到kali里又会出现结果里中文乱码的问题。
> > 
> > 
> > 现在最新的代码在kali跑也有乱码？
> 
> 对，win没有乱码了。
> 
> 刚刚又遇到一个问题
> oneforall.py --target 17wo.cn run
> ![image](https://user-images.githubusercontent.com/15847202/90116719-7a938380-dd88-11ea-9899-2af84c4cffae.png)

好，我先解决这个问题把。

**Comment by shmilylty** [comment]
Invalid IPv6 URL的问题已经解决 可以更新再测试一下https://github.com/shmilylty/OneForAll/commit/091167acb2b48bc3833226da6cefe8aa81e06311

**Comment by shmilylty** [comment]
> **是否使用了最新代码**
> 是
> 
> **Bug描述**
> 今天早上更新到最新版本，发现最终的csv结果文件里的部分子域存在cname,content,public空白，status显示200，本机ping域名也能解析出ip，已测试了10几个域名均如此。
> 
> **运行环境**
> 
> * 系统：Windows 10 x64
> * Python版本：3.8
> * OneForAll版本：2020.8.13
> 
> **如何复现**
> 复现步骤（选写）
> 
> 复现命令（必写）
> 
> **报错文本**
> 复制完整的报错文本（必写）
> 
> **预期结果**
> 清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）
> 
> **实际结果**
> 清晰而简洁的实际结果描述（选写，如出现什么错误）
> 
> **屏幕截图**
> ![image](https://user-images.githubusercontent.com/15847202/90092852-b31d6800-dd5c-11ea-9577-80224e40ac37.png)
> 
> **日志上传**
> 上传oneforall.log日志文件（复杂问题建议上传）
> 
> **其他补充**
> 关于bug的其他一些补充说明

目前这个原因已经找到，晚点修复一下。

**Comment by jhhd88** [comment]
> Invalid IPv6 URL的问题已经解决 可以更新再测试一下[091167a](https://github.com/shmilylty/OneForAll/commit/091167acb2b48bc3833226da6cefe8aa81e06311)

![image](https://user-images.githubusercontent.com/15847202/90123877-14abf980-dd92-11ea-982a-0f21d2ef7640.png)

**Comment by shmilylty** [comment]
> > Invalid IPv6 URL的问题已经解决 可以更新再测试一下[091167a](https://github.com/shmilylty/OneForAll/commit/091167acb2b48bc3833226da6cefe8aa81e06311)
> 
> ![image](https://user-images.githubusercontent.com/15847202/90123877-14abf980-dd92-11ea-982a-0f21d2ef7640.png)

更新再测试一下吧

**Comment by jhhd88** [comment]
> > > Invalid IPv6 URL的问题已经解决 可以更新再测试一下[091167a](https://github.com/shmilylty/OneForAll/commit/091167acb2b48bc3833226da6cefe8aa81e06311)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/15847202/90123877-14abf980-dd92-11ea-982a-0f21d2ef7640.png)
> 
> 更新再测试一下吧

一直卡在Request Progress 83%

**Comment by jhhd88** [comment]
> > > Invalid IPv6 URL的问题已经解决 可以更新再测试一下[091167a](https://github.com/shmilylty/OneForAll/commit/091167acb2b48bc3833226da6cefe8aa81e06311)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/15847202/90123877-14abf980-dd92-11ea-982a-0f21d2ef7640.png)
> 
> 更新再测试一下吧

今天又更新了一下，在Request Progress 84% 卡了大概40分钟以后终于生成报告了。

**Comment by shmilylty** [comment]
> 今天又更新了一下，在Request Progress 84% 卡了大概40分钟以后终于生成报告了。
这个问题我也发现了，貌似是个别现象，比如17wo,cn这个域名就会，我正在调试解决。
