### ISSUE TITLE
qianxun模块不出结果

### ISSUE THREAD

**Issue by jhhd88** [shmilylty/OneForAll#128]
**是否使用了最新代码**
是

**Bug描述**
qianxun模块不出结果，在qianxun网站上手动搜索是可以出结果的。

**运行环境**
 - 系统：Windows 10 x64
 - Python版本：3.8
 - OneForAll版本：0814
 
**如何复现**
复现步骤（选写）

复现命令（必写）
oneforall.py --target xxx.com run
**报错文本**
复制完整的报错文本（必写）

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
测试了很多域名都是如此

**屏幕截图**
![image](https://user-images.githubusercontent.com/15847202/90229749-0241c680-de4b-11ea-8a94-07d6b8297b6e.png)
![image](https://user-images.githubusercontent.com/15847202/90229762-04a42080-de4b-11ea-9a69-472c52e912fb.png)
![image](https://user-images.githubusercontent.com/15847202/90229766-07067a80-de4b-11ea-890e-a286cf609c54.png)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by shmilylty** [comment]
好的，之后测试一下。

**Comment by JrDw0** [comment]
![image](https://user-images.githubusercontent.com/37445725/90462176-dcfad400-e13a-11ea-9835-cee90cafa1a1.png)
![image](https://user-images.githubusercontent.com/37445725/90462199-eab05980-e13a-11ea-996a-9260086868ed.png)
建议单独使用qianxun.py再测试一下？我这边无法复现

**Comment by jhhd88** [comment]
> ![image](https://user-images.githubusercontent.com/37445725/90462176-dcfad400-e13a-11ea-9835-cee90cafa1a1.png)
> ![image](https://user-images.githubusercontent.com/37445725/90462199-eab05980-e13a-11ea-996a-9260086868ed.png)
> 建议单独使用qianxun.py再测试一下？我这边无法复现

还是一样不出结果，网页可以出结果，我试了用代理也一样，我记得以前是可以的，不知道哪天更新了以后就一直不行了，不是特定的域名，而是全部的域名都不会出结果。

**Comment by JrDw0** [comment]
> > ![image](https://user-images.githubusercontent.com/37445725/90462176-dcfad400-e13a-11ea-9835-cee90cafa1a1.png)
> > ![image](https://user-images.githubusercontent.com/37445725/90462199-eab05980-e13a-11ea-996a-9260086868ed.png)
> > 建议单独使用qianxun.py再测试一下？我这边无法复现
> 
> 还是一样不出结果，网页可以出结果，我试了用代理也一样，我记得以前是可以的，不知道哪天更新了以后就一直不行了，不是特定的域名，而是全部的域名都不会出结果。

我测试了一下，理论上只要请求正常返回了至少会发现一个结果（因为这个模块会把输入的目标也返回），而你得到的是0说明你那边的请求返回也不正常了才可能为0，你可以在qianxun.py里打印下resp内容看看
![image](https://user-images.githubusercontent.com/37445725/90490554-56adb480-e171-11ea-89ca-d5d996bf5d97.png)

**Comment by jhhd88** [comment]
> > > ![image](https://user-images.githubusercontent.com/37445725/90462176-dcfad400-e13a-11ea-9835-cee90cafa1a1.png)
> > > ![image](https://user-images.githubusercontent.com/37445725/90462199-eab05980-e13a-11ea-996a-9260086868ed.png)
> > > 建议单独使用qianxun.py再测试一下？我这边无法复现
> > 
> > 
> > 还是一样不出结果，网页可以出结果，我试了用代理也一样，我记得以前是可以的，不知道哪天更新了以后就一直不行了，不是特定的域名，而是全部的域名都不会出结果。
> 
> 我测试了一下，理论上只要请求正常返回了至少会发现一个结果（因为这个模块会把输入的目标也返回），而你得到的是0说明你那边的请求返回也不正常了才可能为0，你可以在qianxun.py里打印下resp内容看看
> ![image](https://user-images.githubusercontent.com/37445725/90490554-56adb480-e171-11ea-89ca-d5d996bf5d97.png)

PyCharm 2020.2 (Professional Edition)
Build #PY-202.6397.98, built on July 27, 2020
Licensed to 永久激活 idea.medeming.com
Subscription is active until September 14, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 12
Non-Bundled Plugins: IdeaVIM

**Comment by jhhd88** [comment]
测试了很多次，执行qianxun.py就能有结果，但是全部模块一起执行就没有结果

**Comment by JrDw0** [comment]
按理说不应该，你保留print这行代码，然后再跑全部的模块，再看看打印出来的resp是否正常？

**Comment by JrDw0** [comment]
没有其他人反馈同样问题，暂时先关闭，还有问题再打开。
