### ISSUE TITLE
--target 文件无法运行

### ISSUE THREAD

**Issue by xsser** [shmilylty/OneForAll#133]
**是否使用了最新代码**
是
**Bug描述**
python3 oneforall.py --target ./domains.txt  run   的时候  domains.txt里的域名不会被运行

**运行环境**
 - 系统：mac os 10.15.6 (19G73)
 - Python版本：3.7.7
 - OneForAll版本：[v0.3.0 #dev
 
**如何复现**
python3 oneforall.py --target ./domains.txt  run 

**报错文本**
[*] Starting OneForAll @ 2020-08-20 15:58:42

15:58:42,308 [INFOR] utils:592 - Checking the environment
15:58:42,308 [INFOR] utils:547 - Checking Internet environment
15:58:42,309 [INFOR] utils:553 - Trying to access http://microsoft.com
15:58:43,744 [INFOR] utils:565 - Access to Internet OK
15:58:43,745 [INFOR] utils:569 - Checking dependent environment
15:58:43,750 [INFOR] utils:603 - Checking for the latest version
15:58:44,753 [INFOR] utils:625 - The current version v0.3.0 is already the latest version
15:58:44,754 [INFOR] oneforall:262 - Start running OneForAll
15:58:44,758 [INFOR] utils:161 - Get 0 domains
15:58:44,759 [ERROR] utils:163 - Did not get a valid domain name
15:58:44,759 [FATAL] oneforall:272 - Failed to obtain domain
15:58:44,759 [INFOR] oneforall:273 - Finished OneForAll

**Comment by tinker-li** [comment]
Nice to meet you.🤣
最新版--target ./domains.txt
改成--targets ./domains.txt

**Comment by shmilylty** [comment]
先关闭issue，如有问题再重开。
