### ISSUE TITLE
OneForAll开启爆破子域名陷入死循环

### ISSUE THREAD

**Issue by broken5** [shmilylty/OneForAll#139]
**是否使用了最新代码**
是

**Bug描述**
爆破子域名时，一直卡在Query xxxxx 's wildcard dns record in authoritative name server

**运行环境**
 - 系统：[Ubuntu16]（必写）
 - Python版本：[Python 3.7.1]（必写）
 - OneForAll版本：[0.3.0]（必写）
 
**如何复现**
复现步骤（选写）

复现命令（必写）
开启子域名爆破的情况下
python3.7 oneforall.py --target  4ggogo.com run 

**报错文本**
复制完整的报错文本（必写）
14:52:24,148 [INFOR] brute:266 - Query 2499b950.4ggogo.com 's wildcard dns record in authoritative name server

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）
![image](https://user-images.githubusercontent.com/46241619/91653140-8c875d00-ead0-11ea-817a-76ed3476db01.png)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by jhhd88** [comment]
![image](https://user-images.githubusercontent.com/15847202/91892219-d46ed580-ecc4-11ea-8472-8eab907e1e29.png)
当设置递归子域3层的时候，还是一样的会出现
