### ISSUE TITLE
GETTING 0 SUBDOMAIN'S RESULT 

### ISSUE THREAD

**Issue by satishkmr834** [shmilylty/OneForAll#142]
13:51:04,140 [INFOR] module:63 - The Finder module took 0.0 seconds found 0 subdomains
13:51:04,160 [ALERT] dbexport:77 - The subdomain result for google.com: /home/satish/tools/OneForAll/results/google.com.csv
13:51:04,169 [ALERT] utils:339 - The subdomain result for all main domains: /home/satish/tools/OneForAll/results/all_subdomain_result_20200907_135104.csv
13:51:04,171 [ALERT] utils:358 - The txt subdomain result for all main domains: /home/satish/tools/OneForAll/results/all_subdomain_result_20200907_135104.txt
13:51:04,171 [INFOR] oneforall:283 - Finished OneForAll

all the time I'm getting 0 subdomains result at the end of scan.

**Comment by JrDw0** [comment]
We need your entire command to find problem

**Comment by satishkmr834** [comment]
python3 oneforall.py --target paypal.com run

![Screenshot from 2020-09-05 16-30-04](https://user-images.githubusercontent.com/31948359/92383104-5b8bd580-f12b-11ea-9484-8d84e373225d.png)

![Screenshot from 2020-09-07 16-45-10](https://user-images.githubusercontent.com/31948359/92383121-60508980-f12b-11ea-9bd5-89b4216d1652.png)
![Screenshot from 2020-09-07 16-45-10](https://user-images.githubusercontent.com/31948359/92383123-60e92000-f12b-11ea-8403-ea70980d84bf.png)

**Comment by satishkmr834** [comment]
![Screenshot from 2020-09-07 16-53-56](https://user-images.githubusercontent.com/31948359/92383224-8d04a100-f12b-11ea-9fe2-dd980c96b74b.png)

**Comment by JrDw0** [comment]
The teminal log show that your DNS resolve failed.

In my opinion, maybe you use wrong dns resolver. 

You can try this:

If your computer's location are not in China, change /config/setting.py 's `brute_nameservers_path` 
`cn_nameservers.txt` to `nameservers.txt` plz.

**Comment by satishkmr834** [comment]
![Screenshot from 2020-09-20 16-56-34](https://user-images.githubusercontent.com/31948359/93710205-75351000-fb62-11ea-9c4a-0d094816ebb4.png)

Hey still its not resolved please do something, i have saved 
cn_nameservers.txt to nameservers.txt also but its not working.

i want to use your tool please.

**Comment by satishkmr834** [comment]
![Screenshot from 2020-09-20 17-04-32](https://user-images.githubusercontent.com/31948359/93710335-731f8100-fb63-11ea-81e8-8c658abc5ba8.png)

**Comment by shmilylty** [comment]
Excuse me, please re-clone the code and try changing cn_nameservers.txt to common_nameservers.txt.
