### ISSUE TITLE
单独使用爆破模块brute.py进行多域名爆破，结果出现严重重复现象

### ISSUE THREAD

**Issue by Little-black** [shmilylty/OneForAll#147]
**是否使用了最新代码**
是

**Bug描述**
在单独使用爆破模块brute.py对大量域名进行自定义的子域名字典爆破时，结果会出现多次重复的情况，并且排越后面的域名重复现象越严重

**运行环境**
 - 系统：Windows 10 x64
 - Python版本：3.7.0
 - OneForAll版本：2020.9.28最新代码
 
**如何复现**
复现步骤（选写）
1、将域名列表domains.txt放入oneforall根目录下，里面大概有400个不重复的域名。
2、将子域名字典subnames.txt放入oneforall根目录下，里面有100个不重复的子域名。
3、运行命令，然后去results目录查看结果
4、发现前面的域名结果很正常，但是后面的域名结果里面同样的子域名开始重复出现，越后面的域名，重复次数越多。

复现命令（必写）
python3 brute.py --targets domains.txt --word True --wordlist subnames.txt run

**报错文本**
无

**预期结果**
每个域名的爆破结果生成一个csv文件保存在results目录下，结果内容不会重复。

**实际结果**
随着域名爆破的进行，重复现象越来越严重。疑似对列表中下一个域名进行爆破时，子域名字典会重复加载一遍。

**屏幕截图**
（1）oneforall运行截图
![1](https://user-images.githubusercontent.com/36403011/94403405-f6625780-019f-11eb-866d-66ef02724808.PNG)

（2）domains.txt中排较前面的域名的爆破结果
![2](https://user-images.githubusercontent.com/36403011/94403633-4e00c300-01a0-11eb-8d42-bb4826371422.PNG)

（3）domians.txt中排较后面的域名的爆破结果
![3](https://user-images.githubusercontent.com/36403011/94403673-5a851b80-01a0-11eb-8ed9-e84e9537162a.PNG)

**日志上传**
无

**其他补充**
第（1）张截图中，这里想问一下师傅，根据提示语句，在红线处子域名就已经爆破完成了，为节省时间，红线下面的流程可否省略，如果可以该如何省略。

**Comment by shmilylty** [comment]
方便上传domains.txt和subnames.txt吗
