### ISSUE TITLE
Cannot allocate memory failure

### ISSUE THREAD

**Issue by Dialem** [shmilylty/OneForAll#149]
Hi
Like other people, there is a problem when the program does not have enough memory. I have 36 gigabytes of RAM free, but Oneforall manages to stop there as well. The "Cannot allocate memory failure" error occurs. The error falls out on 36 thousand domains. Checking for mail.ru

**Comment by shmilylty** [comment]
OK, thanks for the feedback. We are currently doing memory optimization.

**Comment by shmilylty** [comment]
The latest version has been optimized for memory, so you can update OneForAll and retest it.
