### ISSUE TITLE
sqlit结果未保存

### ISSUE THREAD

**Issue by HenryLee8129** [shmilylty/OneForAll#151]
**是否使用了最新代码**
是

**Bug描述**
terminal界面有结果输出，最后temp目录有结果，但是results文件以及sqlit中无数据，文件大小为

**运行环境**
 - 系统：Windows 7 x64以及kali2020
 - Python版本：[例如3.7.1]
 - OneForAll版本：最新
 
**如何复现**
复现步骤（选写）

复现命令（必写）
python3 oneforall.py --target baidu.com run
**报错文本**
复制完整的报错文本（必写）

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）
![image](https://user-images.githubusercontent.com/20028305/95568582-ff341280-0a56-11eb-94f3-c4b8eb578028.png)
![image](https://user-images.githubusercontent.com/20028305/95568671-1bd04a80-0a57-11eb-9bce-c21ee165e0d1.png)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by shmilylty** [comment]
使用最新版本再试一下呢

**Comment by shmilylty** [comment]
问题和 #152 重复，关闭此问题。
