### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'seek'

### ISSUE THREAD

**Issue by cell13** [shmilylty/OneForAll#154]
**是否使用了最新代码**
是

**Bug描述**
AttributeError: 'WindowsPath' object has no attribute 'seek'

**运行环境**
 - 系统：Windows 10 x64
 - Python版本：3.6.1
 - OneForAll版本：git clone 最新版本
 
**如何复现**
cd OneForAll/
python3 -m pip install -U pip setuptools wheel -i https://mirrors.aliyun.com/pypi/simple/
pip3 install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
python3 oneforall.py --help

**复现命令（必写）**
python3 oneforall.py --help

**报错文本**
AttributeError: 'WindowsPath' object has no attribute 'seek'

**预期结果**
正常运行

**实际结果**
提示报错

**Comment by shmilylty** [comment]
已经更新，表哥可以再测试一下。
