### ISSUE TITLE
代理配置失误

### ISSUE THREAD

**Issue by windmoon-Lotus** [shmilylty/OneForAll#157]
设置代理地址和全局代理，任未成功连接谷歌，请问是网络检测的方式的问题还是配置不对？
配置
request_proxy_pool = [{'http': 'http://127.0.0.1:10809',
                       'https': 'https://127.0.0.1:10809'}] 
![image](https://user-images.githubusercontent.com/69948103/96421042-de26ab00-1228-11eb-9a3b-490b42b7a7ff.png)
我自身可访问Google

**Comment by shmilylty** [comment]
你在群里吗，可以在群里反馈交流一下。

**Comment by windmoon-Lotus** [comment]
刚加群
