### ISSUE TITLE
dns.exception.Timeout: The DNS operation timed out after 10.004592180252075 seconds

### ISSUE THREAD

**Issue by Bi3g0** [shmilylty/OneForAll#160]
**是否使用了最新代码**
是的

**Bug描述**
海外机器上，在Detecting x.com.cn use wildcard dns record or not后提示查询失败，超时错误。之后不断循环报错，继续查询超时。国内机器上没有问题。

**运行环境**
 - 系统：
Ubuntu 18.04.4 LTS x86_64
 - Python版本：
Python 3.8.3(国内机器)
Python 3.8.5（海外机器）

 - OneForAll版本：
v0.3.0 #dev
 
**如何复现**
复现步骤（选写）
国内机器执行成功：
python oneforall.py --target  x.com.cn run
海外执行失败。

复现命令（必写）

**报错文本**
海外机器：
`08:12:24,923 [INFOR] brute:137 - Detecting *.com.cn use wildcard dns record or not
08:12:25,173 [ALERT] brute:76 - ****.com.cn resolve to: ****.com.cn. IP: {'210.83.*.*', '218.18.*.*', '124.196.*.*'} TTL: 600
08:12:25,423 [ALERT] brute:76 - ****.com.cn resolve to: 0*****.*.com.cn. IP: {'210.83.*.*', '218.18.*.*', '124.196.*.*'} TTL: 600
08:12:25,675 [ALERT] brute:76 - b*****.*.com.cn resolve to: ****.com.cn. IP: {'210.83.*.*', '218.18.*.*', '124.196.*.*'} TTL: 600
08:12:25,676 [INFOR] utils:704 - Attempting to request http://f****.com.cn
08:12:35,322 [ALERT] utils:712 - Error request http://f****.com.cn
08:12:35,323 [INFOR] utils:704 - Attempting to request http://0****.com.cn
08:12:45,504 [ALERT] utils:712 - Error request http://0****.com.cn
08:12:45,506 [INFOR] utils:704 - Attempting to request http://b3****.com.cn
08:12:55,590 [ALERT] utils:712 - Error request http://b****.com.cn
08:12:55,591 [ALERT] brute:150 - The domain *.com.cn enables wildcard
08:12:55,592 [INFOR] brute:297 - Collecting wildcard dns record for *.com.cn
08:12:55,593 [INFOR] brute:266 - Query 2****.com.cn 's wildcard dns record in authoritative name server
08:13:05,600 [ALERT] brute:272 - Query timeout, retrying
08:13:05,601 [INFOR] brute:266 - Query 2*****.*.com.cn 's wildcard dns record in authoritative name server
08:13:15,606 [ALERT] brute:272 - Query timeout, retrying
--- Logging error in Loguru Handler #2 ---
Record was: None
Traceback (most recent call last):
  File "/root/bayonet/tools/OneForAll/brute.py", line 269, in get_wildcard_record
    answer = resolver.query(domain, 'A')
  File "/root/miniconda3/envs/py3/lib/python3.8/site-packages/dns/resolver.py", line 900, in query
    timeout = self._compute_timeout(start, lifetime)
  File "/root/miniconda3/envs/py3/lib/python3.8/site-packages/dns/resolver.py", line 799, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 10.004592180252075 seconds

During handling of the above exception, another exception occurred:`

**Comment by shmilylty** [comment]
收到，在群里私聊我反馈一下。

**Comment by shmilylty** [comment]
此问题已修复
