### ISSUE TITLE
what is "RMH-14" org? it's anomaly subdomains and inactive all

### ISSUE THREAD

**Issue by foozzi** [shmilylty/OneForAll#164]
these subdomains appeared in version 0.4.1

**Comment by shmilylty** [comment]
I'm not sure what question you want to ask. Can you describe it in more detail?

**Comment by foozzi** [comment]
> I'm not sure what question you want to ask. Can you describe it in more detail?

I get a lot of subdomains with "org" - hosting "RMH-14", all these domains are not active, but apparently they existed once. Where does OneForAll find them? Older versions did not have this

**Comment by JrDw0** [comment]
You can check module or source field, it show which module and where OneForAll find the subdomain.
