### ISSUE TITLE
无法使用爆破模块

### ISSUE THREAD

**Issue by SummerSec** [shmilylty/OneForAll#165]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
是

**Bug描述**
清晰而简洁的Bug描述（必写）
无法使用爆破模块

**运行环境**
 - 系统：[例如Windows 10 x64]（必写）
Windows10 X64
 - Python版本：[例如3.7.1]（必写）
3.8
 - OneForAll版本：[例如0.3.0]（必写）
0.41
 
**如何复现**
复现步骤（选写）

复现命令（必写）

**报错文本**
复制完整的报错文本（必写）

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）
![image](https://user-images.githubusercontent.com/47944478/99892614-72b17c80-2cb1-11eb-8c41-0b50fa8fbc37.png)

**屏幕截图**
完整OneForAll执行流程截图（建议上传）
![image](https://user-images.githubusercontent.com/47944478/99892614-72b17c80-2cb1-11eb-8c41-0b50fa8fbc37.png)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by shmilylty** [comment]
需要指定fuzz的位置，请仔细看一下帮助信息。
