### ISSUE TITLE
請問 --alive 與 --req 參數是衝突的嗎

### ISSUE THREAD

**Issue by mangodmai** [shmilylty/OneForAll#168]
**是否使用了最新代码**
是

**Bug描述**
請問 --alive 與 --req 參數是衝突的嗎, 兩個參數都用的話 result 的文件為空, 只用其中一個就能正常顯示結果.

**运行环境**
 - 系统：Kali
 - Python版本：3.8
 - OneForAll版本：0.4.3

**Comment by shmilylty** [comment]
--alive和--req参数不冲突，--alive是指导出时只导出存活的子域，而--req表示是否进行子域请求。
