### ISSUE TITLE
oneforall took a huge mount of time to excute

### ISSUE THREAD

**Issue by ahmedhamada** [shmilylty/OneForAll#169]
**Whether the latest code is used**
Yes or no (if not, try to clone the latest code and run again!)

**Bug description**
Clear and concise Bug description(required)

**Operation environment**
 - System information: kali
 - Python version: python 3.8.6
 - OneForAll version: 0.4.3
 
**How to reproduce**
1. run oneforall on uber target
   oneforall.py --target uber.com run

![Screenshot_2020-12-06_21-56-59](https://user-images.githubusercontent.com/11416367/101288463-72f85e80-37ff-11eb-8526-41c876bbef4c.png)
![Screenshot_2020-12-06_21-56-31](https://user-images.githubusercontent.com/11416367/101288464-74298b80-37ff-11eb-8dc3-6bf9ef778337.png)

**Comment by JrDw0** [comment]
Can't repeat the issue, Please try again with the latest version. The problem is closed for the time being.
