### ISSUE TITLE
readme 中一处链接大小写错误

### ISSUE THREAD

**Issue by No-Github** [shmilylty/OneForAll#17]
上手指南-->安装步骤 中，依赖安装指向
`https://github.com/shmilylty/OneForAll/tree/master/docs/installation_dependency.md`
因改为
`https://github.com/shmilylty/OneForAll/tree/master/docs/Installation_dependency.md`
大小写问题😂

**Comment by shmilylty** [comment]
已解决 https://github.com/shmilylty/OneForAll/commit/bc9b5b0afe5aea55eb63558ae805b86542d7fd62
