### ISSUE TITLE
运行的时候，大量提示连接尝试次数过多

### ISSUE THREAD

**Issue by littleheary** [shmilylty/OneForAll#172]
报错内容如下：
HTTPSConnectionPool(host='www.sogou.com', port=443): Max retries exceeded with url: /web?query=site%3A.boc.cn&page=2&num=50 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f79fc447e48>, 'Connection to www.sogou.com timed out. (connect timeout=3.05)'))

很多被访问的搜索引擎都报这个错误。

**Comment by shmilylty** [comment]
可以尝试把超时设置大一点
