### ISSUE TITLE
v0.4.3爆破模块问题

### ISSUE THREAD

**Issue by Corgizz** [shmilylty/OneForAll#174]
使用命令：python3 oneforall.py --targets ./domains.txt --alive True --brute True --port small run

跑出来域名source栏，都是些其他三方接口查询出来的域名，没有Brute

尝试oneforall 0.3.0版本，同样域名（多个域名），同样字典，能跑出一些爆破出来域名，而在0.4.3版本没有爆破出来域名显示

**Comment by jhhd88** [comment]
从这次https://github.com/shmilylty/OneForAll/commit/82e0180a17d91d0405541da90eb230e72be67471  更新以后就没有brute结果了。

**Comment by Corgizz** [comment]
后续是不加入brute模块？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jhhd88"<notifications@github.com&gt;; 
发送时间: 2021年1月11日(星期一) 凌晨2:59
收件人: "shmilylty/OneForAll"<OneForAll@noreply.github.com&gt;; 
抄送: "十八"<812358080@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shmilylty/OneForAll] v0.4.3爆破模块问题 (#174)





 
从这次82e0180  更新以后就没有brute结果了。

**Comment by shmilylty** [comment]
收到，我后面排查一下。

**Comment by Corgizz** [comment]
还有个问题，新版获取title时，默认是CVS格式显示为空，0.3.0可以获取得到title显示，格式xlsx



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jing Ling"<notifications@github.com&gt;; 
发送时间: 2021年1月11日(星期一) 中午11:36
收件人: "shmilylty/OneForAll"<OneForAll@noreply.github.com&gt;; 
抄送: "十八"<812358080@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shmilylty/OneForAll] v0.4.3爆破模块问题 (#174)





 
收到，我后面排查一下。

**Comment by 5z1punch** [comment]
除了上面这个 pr 修的问题，还有一个问题，enable_dns_resolve 这个开关和 result_export_alive 这个开关本身是冲突的，然而默认都是 True

**Comment by shmilylty** [comment]
> 除了上面这个 pr 修的问题，还有一个问题，enable_dns_resolve 这个开关和 result_export_alive 这个开关的默认配置是冲突的

具体冲突是指什么呢

**Comment by 5z1punch** [comment]
啊，又看了下代码，可能我对 alive 的理解有偏差，应该没有啥冲突 😂，木事了 

> > 除了上面这个 pr 修的问题，还有一个问题，enable_dns_resolve 这个开关和 result_export_alive 这个开关的默认配置是冲突的
> 
> 具体冲突是指什么呢@5z1punch

**Comment by shmilylty** [comment]
alive是指dns解析成功，http请求正常(状态码为400或大于500不算正常)。 @5z1punch

**Comment by shmilylty** [comment]
@jhhd88 @Corgizz 表哥们请验证最新的代码是否还存在该问题。

**Comment by Corgizz** [comment]
我只知道爆破问题，修复了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jing Ling"<notifications@github.com&gt;; 
发送时间: 2021年1月29日(星期五) 下午2:18
收件人: "shmilylty/OneForAll"<OneForAll@noreply.github.com&gt;; 
抄送: "十八"<812358080@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [shmilylty/OneForAll] v0.4.3爆破模块问题 (#174)





 
@jhhd88 @Corgizz 表哥们请验证最新的代码是否还存在该问题。
