### ISSUE TITLE
不开启req就无法获取搜集子域名的结果吗（最新版取消了verify等参数）

### ISSUE THREAD

**Issue by p1g3** [shmilylty/OneForAll#175]
**是否使用了最新代码**
是

**Bug描述**
没有办法在关闭req的情况下获得所搜集到的子域名（只想搜集子域名，不想发出任何与子域名有关联的请求）。看之前issue有人提过，师傅的回答是把verify设置为False，但是我看最新版似乎已经取消了这个选项？

**运行环境**
 - 系统：OS X
 - Python版本：3.8.0
 - OneForAll版本：0.4.3
 
**如何复现**
复现命令 python3 test.py
```
#!/usr/bin/env python3
# coding=utf-8

"""
Example
"""

from oneforall import OneForAll


def oneforall(domain):
    test = OneForAll(target=domain)
    test.brute = False
    test.req = False
    test.takeover = False
    test.run()
    print(test.datas)


if __name__ == '__main__':
    oneforall('freebuf.com')
```

**报错文本**
无

**预期结果**
正常情况应获取所有的子域名详情列表（翻看了一下代码，似乎没有将所搜集的子域名保存到某个属性中？）

**实际结果**
返回的列表为空。

**Comment by shmilylty** [comment]
test.req = False即不进行http请求，test.datas即收集结果。

**Comment by p1g3** [comment]
你可以自己试试，代码有些Bug，我测试Freebuf不开启req无法获取datas。

Jing Ling <notifications@github.com> 于2021年1月16日周六 下午3:36写道：

**Comment by shmilylty** [comment]
好的 我看一下原因

**Comment by shmilylty** [comment]
之前忘了加了，已经修改了，师傅可以重新测试一下，有问题反馈一下。
