### ISSUE TITLE
Error sending: Operation not permitted

### ISSUE THREAD

**Issue by ghost** [shmilylty/OneForAll#186]
按照git那里的说明安装成功， 运行一段时间后无限打印:
Error sending: Operation not permitted
Error sending: Operation not permitted
Error sending: Operation not permitted
Error sending: Operation not permitted
Error sending: Operation not permitted
Error sending: Operation not permitted
Error sending: Operation not permitted
Error sending: Operation not permitted
Error sending: Operation not permitted
Error sending: Operation not permitted
Error sending: Operation not permitted
Error sending: Operation not permitted
Error sending: Operation not permitted
Error sending: Operation not permitted

系统:
Debian GNU/Linux bullseye/sid \n \l
Debian 5.10.9-1 (2021-01-20) x86_64 GNU/Linux

**Comment by shmilylty** [comment]
这个好像是massdns的问题，可以去[massdns](https://github.com/blechschmidt/massdns/issues)开个issue问问。
