### ISSUE TITLE
docker 运行提示ERROR: Could not consume arg: —-target

### ISSUE THREAD

**Issue by 513379690** [shmilylty/OneForAll#187]
docker run -it --rm -v /System/Volumes/Data/web/oneforall/results:/OneForAll/results -v /System/Volumes/Data/web/oneforall/config:/OneForAll/config shmilylty/oneforall —-target ***.cn run
ERROR: Could not consume arg: —-target
Usage: oneforall.py - <group|command|value>
  available groups:      data | datas | domains
  available commands:    check | check_param | config_param | export_data |
                         main | run | version
  available values:      access_internet | alive | brute | dns | domain |
                         enable_wildcard | fmt | in_china | path | port | req |
                         takeover | target | targets

For detailed information on this command, run:
  oneforall.py - --help

**Comment by Tardis07** [comment]
The argument should be `--target` while you're using `—-target`. There should be two dashes before 'target', not em dash.
