### ISSUE TITLE
github的api搜索语法显示错误

### ISSUE THREAD

**Issue by sv3nbeast** [shmilylty/OneForAll#188]
**是否使用了最新代码**
是

**Bug描述**
语法错误报422，bp抓的oneforall访问github api的包，

![image](https://user-images.githubusercontent.com/55974091/107339265-7659e000-6af7-11eb-9ecb-1b1d171cd29d.png)

**运行环境**
 - 系统：mac
 - Python版本：3.8.7
 - OneForAll版本：最新
 
**如何复现**
复现步骤（选写）

复现命令（必写）

**报错文本**
复制完整的报错文本（必写）

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by sv3nbeast** [comment]
附参考文章，错误语法会导致报422状态码
https://blog.csdn.net/next_second/article/details/78238328

**Comment by shadow1ng** [comment]
将token写在url里即可，&access_token=ghp_xxxxxxxxxxx
![image](https://user-images.githubusercontent.com/39651966/123576989-8f90ce00-d805-11eb-9628-5e18fc4ebf7c.png)

https://stackoverflow.com/questions/24132790/how-to-search-for-code-in-github-with-github-api

**Comment by jhhd88** [comment]
![image](https://user-images.githubusercontent.com/15847202/123589887-7cd5c380-d81c-11eb-93f8-22d23147d433.png)
