### ISSUE TITLE
Error wildcard

### ISSUE THREAD

**Issue by myuyu** [shmilylty/OneForAll#190]
**Whether the latest code is used**
Yes

**Bug description**
When try to run oneforall.py it return wildcard error

**Operation environment**
 - System information: Ubuntu x86_64
 - Python version: 3.8.6
 - OneForAll version: The latest version
 
**How to reproduce**
1. Step (optional)

2. Command (required)
python3 oneforall.py [ Any Option ]
**Error text**
```
root@XX:~/OneForAll# python3 oneforall.py
Traceback (most recent call last):
  File "oneforall.py", line 16, in <module>
    from brute import Brute
  File "/root/OneForAll/brute.py", line 25, in <module>
    from modules import wildcard
ImportError: cannot import name 'wildcard' from 'modules' (/usr/local/lib/python3.8/dist-packages/modules.py)
root@XXX:~/OneForAll# python oneforall.py
```

**Expected results**
A clear and concise description of the expected results (optional, such as what a normal situation should look like)

**Actual results**
A clear and concise description of the actual results (optional, such as any errors)

**Screenshot**
Screenshot of complete OneForAll execution process (recommended upload)

**Log upload**
Upload oneforall.log files (it is recommended to upload logs in case of complex problems)

**Supplementary information**
Some other supplementary notes about bug

**Comment by shmilylty** [comment]
try to uninstall `modules`:
```shell
pip3 uninstall modules
```
and then try to run OneForAll.
