### ISSUE TITLE
在cmder下已填写目标参数报错缺少target参数

### ISSUE THREAD

**Issue by swx338** [shmilylty/OneForAll#196]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
是
**Bug描述**
清晰而简洁的Bug描述（必写）
已填写目标参数报错缺少target参数
**运行环境**
 - 系统：[例如Windows 10 x64]（必写）
 - win10
 - Python版本：[例如3.7.1]（必写）
 - 3.8
 - OneForAll版本：[例如0.3.0]（必写）
 - v0.4.3
 
**如何复现**
复现步骤（选写）
cmder工具 运行该脚本，无法正常使用，powershell正常使用
复现命令（必写）
python oneforall.py --tartget njmu.edu run
**报错文本**
复制完整的报错文本（必写）
python oneforall.py --tartget njmu.edu run

OneForAll is a powerful subdomain integration tool
             ___             _ _
 ___ ___ ___|  _|___ ___ ___| | | {v0.4.3 #dev}
| . |   | -_|  _| . |  _| .'| | |
|___|_|_|___|_| |___|_| |__,|_|_| git.io/fjHT1

OneForAll is under development, please update before each use!

[*] Starting OneForAll @ 2021-04-16 15:30:52

15:30:52,962 [INFOR] utils:523 - Checking dependent environment
15:30:52,962 [INFOR] utils:535 - Checking network environment
15:30:53,511 [INFOR] utils:546 - Checking for the latest version
15:30:54,422 [INFOR] utils:570 - The current version v0.4.3 is already the latest version
15:30:54,423 [INFOR] oneforall:243 - Start running OneForAll
15:30:54,423 [FATAL] oneforall:131 - You must provide either target or targets parameter

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）
![image](https://user-images.githubusercontent.com/52640674/114988873-68468800-9ec9-11eb-83b9-822cba1e3aa3.png)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by swx338** [comment]
运行示例代码命令正常，针对其他域名报错。
python oneforall.py --target example.com run
虽然cmder下不能用，powershell中可以用，但是示例命令可以运行，baidu.com也是可以的，所以可能程序有点bug

**Comment by shmilylty** [comment]
从你给的截图来看你把target打错成tartget了
