### ISSUE TITLE
目标域名如果存在跳转 我觉得应该属于存活

### ISSUE THREAD

**Issue by k0njac** [shmilylty/OneForAll#198]
**是否使用了最新代码**
是

**Bug描述**
vpn.acewill.net
类似这种带跳转的域名应该算做存活 但是似乎并没有出现在结果里面

**运行环境**
 - 系统：[例如Windows 10 x64]（必写）
 - Python版本：[例如3.7.1]（必写）
 - OneForAll版本：[例如0.3.0]（必写）
 
**如何复现**
复现步骤（选写）
开启爆破模式，字典存在 vpn 这个字段

复现命令（必写）
 python .\oneforall.py --target acewill.net run

**预期结果**
扫描结果应该存在vpn.acewill.net

**实际结果**
并没有显示这个结果存活

**Comment by shmilylty** [comment]
vpn.acewill.net跳转之后并不能正常访问

**Comment by k0njac** [comment]
![image](https://user-images.githubusercontent.com/72721956/118762861-7eb97800-b8a9-11eb-96d7-dc0f8db9c9d5.png)
可以正常访问

**Comment by JrDw0** [comment]
时间太久，已无法访问vpn.acewill.net重现问题，先关闭
