### ISSUE TITLE
一直报sqlite3的错误

### ISSUE THREAD

**Issue by fnmsd** [shmilylty/OneForAll#2]
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 17616 and this is thread id 17904.

**Comment by shmilylty** [comment]
克隆最新版本的试试呢

**Comment by fnmsd** [comment]
就是直接Clone，本地python 3.7.3

**Comment by shmilylty** [comment]
先执行git pull更新以下

**Comment by shmilylty** [comment]
已解决
