### ISSUE TITLE
在运行的时候无法检测到网络环境的存在

### ISSUE THREAD

**Issue by AMG4MATIC** [shmilylty/OneForAll#200]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
是
**Bug描述**
清晰而简洁的Bug描述（必写）
在运行的时候无法检测到网络环境的存在
**运行环境**
 - 系统：[macOS 11.1 x64]（必写）
 - Python版本：[3.8.6]（必写）
 - OneForAll版本：[0.4.3]（必写）
 
**如何复现**
复现步骤（选写）
运行test.py即可复现
复现命令（必写）
python test.py
python3 oneforall.py --targets cdcyy run
**报错文本**
复制完整的报错文本（必写）
(MaxRetryError("HTTPConnectionPool(host='ipinfo.io', port=80): Max retries exceeded with url: /json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x10a1fd8e0>, 'Connection to ipinfo.io timed out. (connect timeout=13)'))"),)
**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）
正常情况应联网对目标站点执行检测。
**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）
oneforall.main:153 - Because it cannot access the Internet, OneForAll will not execute the subdomain collection module!
**屏幕截图**
完整OneForAll执行流程截图（建议上传）
![image](https://user-images.githubusercontent.com/47023007/118454726-44c26780-b72b-11eb-8255-6865e1451367.png)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by jhhd88** [comment]
+1，我还以为是我电脑问题，不知道是不是更新了系统补丁导致的，突然出现的。 5月12号都还正常运行

**Comment by jhhd88** [comment]
用Proxifier走一层代理是可以正常运行，但结果会不准。

**Comment by jhhd88** [comment]
OneForAll\common\utils.py  498行改成https://api.ip.sb/geoip
![QQ图片20210517175721](https://user-images.githubusercontent.com/15847202/118470526-57dc3400-b739-11eb-8693-af2ef9ad7e7e.png)

**Comment by AMG4MATIC** [comment]
> https://api.ip.sb/geoip

666，看起来似乎是ipinfo服务被🧱或者挂了导致的，感谢提供的解决方案

**Comment by AMG4MATIC** [comment]
> OneForAll\common\utils.py 498行改成https://api.ip.sb/geoip
> ![QQ图片20210517175721](https://user-images.githubusercontent.com/15847202/118470526-57dc3400-b739-11eb-8693-af2ef9ad7e7e.png)

@jhhd88 666，感谢提供的解决方案，看来是ipinfo提供的服务被🧱或者挂了导致的

**Comment by jhhd88** [comment]
原来的两个站，一个被墙，一个502

**Comment by AMG4MATIC** [comment]
再提供一个API，http://ip-api.com/json/

**Comment by shmilylty** [comment]
感谢反馈，已做修改。
