### ISSUE TITLE
KeyError: "name='netcraft_js_verification_challenge', domain=None, path=None"

### ISSUE THREAD

**Issue by Corgizz** [shmilylty/OneForAll#201]
oneforall 最新版
python3.8以上
win 10

之前是无法检查网络环境，替换为https://api.ip.sb/geoip，就出现bug

![image](https://user-images.githubusercontent.com/33239583/118584479-98838e00-b7c9-11eb-9fba-1f78a0af6ae1.png)

GET http://114.55.181.28/check_web/databaseInfo_mainSearch.action?isSearch=true&searchType=url&term=xx.com&pageNo=1 404 - Not Found 5042

**Comment by shmilylty** [comment]
感谢反馈，netcraft改了相应反爬策略，之后优化一下。

**Comment by shmilylty** [comment]
已修复
