### ISSUE TITLE
ImportError: cannot import name 'wildcard' from 'modules'

### ISSUE THREAD

**Issue by sinner-user** [shmilylty/OneForAll#202]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）

**Bug描述**
清晰而简洁的Bug描述（必写）

**运行环境**
 - 系统：Windows 10 x64（必写）
 - Python版本：3.8.6（必写）
 - OneForAll版本：0.4.3（必写）
 
使用python3.exe oneforall.py --target baidu.com run 报错
报错详情
Traceback (most recent call last):
  File "oneforall.py", line 16, in <module>
    from brute import Brute
  File "E:\tool\信息收集\子域名扫描\OneForAll-master（子域名收集）\brute.py", line 25, in <module>
    from modules import wildcard
ImportError: cannot import name 'wildcard' from 'modules' (D:\python\python3.8\lib\site-packages\modules.py)

**Comment by shmilylty** [comment]
卸载modules包，重试一下。
```shell
pip3 uninstall modules
```

**Comment by iamhesy** [comment]
卸载了 modules 就行了
