### ISSUE TITLE
OneForAll Errors When Running in Folder With Spaces

### ISSUE THREAD

**Issue by NoPurposeInLife** [shmilylty/OneForAll#204]
Hi!

OneForAll encounters an error after brute.py in line 446 if it is executed from a director with whitespace. Tested on Windows 10 x64, where it shows 'C:\\Users\\Admin\\Tools' is not recognized as an internal or external command when running with "py -3 oneforall.py --target example.com run". The example full path is 'C:\\Users\\Admin\\Tools Directory\\OneForAll\\oneforall.py' where in the end, it results in a file not found error of "C:\\Users\\Admin\\Tools Directory\\\\OneForAll\\results\\temp\\resolved_result_example.com_20210530_082959.json"

**Comment by shmilylty** [comment]
This problem has been discovered so far, please avoid using spaces for now, we will try to fix this problem later.
