### ISSUE TITLE
无限随机域名查询 997ea80c.anantest.com

### ISSUE THREAD

**Issue by godzeo** [shmilylty/OneForAll#206]
**是否使用了最新代码**
是

**Bug描述**
无限使用随机域名探测cdn，死循环结束不了

**运行环境**
 - 系统：macos 15.1
 - Python版本 3.7.1
 - OneForAll版本：0.3.4]
 
**如何复现**
对 www.anantest.com 这个域名默认配置扫描即可

21:57:18,545 [ALERT] wildcard:179 - Multiple query errors,try to query a new random subdomain
21:57:18,546 [INFOR] wildcard:129 - Query 55c435f5.anantest.com 's wildcard dns record in authoritative name server
21:57:28,551 [ALERT] wildcard:135 - Query timeout, retrying

**报错文本**

**预期结果**
应该试几个随机域名不行就停了吧

**实际结果**
无限循环
21:56:58,538 [ALERT] wildcard:179 - Multiple query errors,try to query a new random subdomain
21:56:58,538 [INFOR] wildcard:129 - Query 997ea80c.anantest.com 's wildcard dns record in authoritative name server
21:57:08,542 [ALERT] wildcard:135 - Query timeout, retrying
21:57:08,542 [INFOR] wildcard:129 - Query 997ea80c.anantest.com 's wildcard dns record in authoritative name server
21:57:18,545 [ALERT] wildcard:135 - Query timeout, retrying
21:57:18,545 [ALERT] wildcard:179 - Multiple query errors,try to query a new random subdomain
21:57:18,546 [INFOR] wildcard:129 - Query 55c435f5.anantest.com 's wildcard dns record in authoritative name server
21:57:28,551 [ALERT] wildcard:135 - Query timeout, retrying
21:57:28,551 [INFOR] wildcard:129 - Query 55c435f5.anantest.com 's wildcard dns record in authoritative name server
21:57:38,556 [ALERT] wildcard:135 - Query timeout, retrying
21:57:38,557 [ALERT] wildcard:179 - Multiple query errors,try to query a new random subdomain
21:57:38,557 [INFOR] wildcard:129 - Query 275331f3.anantest.com 's wildcard dns record in authoritative name server
21:57:48,559 [ALERT] wildcard:135 - Query timeout, retrying
21:57:48,559 [INFOR] wildcard:129 - Query 275331f3.anantest.com 's wildcard dns record in authoritative name server
21:57:58,560 [ALERT] wildcard:135 - Query timeout, retrying
21:57:58,561 [ALERT] wildcard:179 - Multiple query errors,try to query a new random subdomain
21:57:58,562 [INFOR] wildcard:129 - Query 5a2603b3.anantest.com 's wildcard dns record in authoritative name server
21:58:08,567 [ALERT] wildcard:135 - Query timeout, retrying
21:58:08,567 [INFOR] wildcard:129 - Query 5a2603b3.anantest.com 's wildcard dns record in authoritative name server

**屏幕截图**

**日志上传**

**其他补充**
关于bug的其他一些补充说明

**Comment by je5442804** [comment]
手动修改 modules/wildcard.py 中 get_wildcard_record方法 ，except Timeout as e: 下，直接吧raise e替换为 
return None, None @godzeo
