### ISSUE TITLE
子域名结果中有"垃圾域名"

### ISSUE THREAD

**Issue by leveryd** [shmilylty/OneForAll#213]
**是否使用了最新代码**
是

**Bug描述**

python3 oneforall.py --target wwdmas.cn run

最终结果中有 000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.wwdmas.cn,000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.000.wwdmas.cn
这种域名

**运行环境**
 - 系统：Mac
 - Python版本：3.7
 - OneForAll版本：2021-7-31最新master分支
 
**如何复现**
python3 oneforall.py --target wwdmas.cn run

**屏幕截图**

**Comment by shmilylty** [comment]
收到 之后会统一处理一下

**Comment by leveryd** [comment]
我打算在nsec模块检查子域名中是否有 "000"关键字，来屏蔽掉。需要我提交一个pr嘛？

**Comment by shmilylty** [comment]
谢谢师傅反馈 已经做了修改
