### ISSUE TITLE
[BUG] crt.sh可以查到域名，但是oneforall结果中未包含

### ISSUE THREAD

**Issue by leveryd** [shmilylty/OneForAll#218]
**是否使用了最新代码**
是

**Bug描述**

python3 oneforall.py --target huawei.com run

最终结果中没有 www.hwworks-live-route.huawei.com。

但访问 https://crt.sh/?q=huawei.com ，能看到此域名

**运行环境**
 - 系统：Mac
 - Python版本：3.7
 - OneForAll版本：2021-7-31最新master分支
 
**如何复现**
python3 oneforall.py --target huawei.com run

**屏幕截图**
![image](https://user-images.githubusercontent.com/1846319/129063157-a763e5a5-2d17-4859-9038-f03f6c1e69f8.png)

**Comment by shmilylty** [comment]
最新版本复测了一下，可以收集到www.hwworks-live-route.huawei.com

![image](https://user-images.githubusercontent.com/24275308/203250534-002476d0-b540-43a1-93ce-7a3f93477992.png)

但是这个域名不能解析
```
Ping 请求找不到主机 www.hwworks-live-route.huawei.com。请检查该名称，然后重试。
```
你可以看看最终结果是否有为解析成功的www.hwworks-live-route.huawei.com
