### ISSUE TITLE
结果csv文件中文乱码

### ISSUE THREAD

**Issue by xiaoheiwo** [shmilylty/OneForAll#22]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下）
是
**Bug描述**
清晰而简洁的Bug描述

cvs结果文件 中文乱码

**如何复现**
复现步骤（可不写）
复现命令

**预期结果**
清晰而简洁的预期结果描述（可不写）

**实际结果**
清晰而简洁的实际结果描述（如出现什么错误）
打开cvs结果 中文都是乱码
**屏幕截图**

![image](https://user-images.githubusercontent.com/37685546/65134348-bc139580-da36-11e9-8cdb-8bc974a8c03b.png)

**运行环境**
 - 系统：[例如Windows 10 x64]
 - Python版本：[例如3.7.1]
- OneForAll版本：[例如0.0.6]

**报错文本**
复制完整的报错文本

**Comment by shmilylty** [comment]
https://github.com/shmilylty/OneForAll/blob/master/docs/Q%26A.md

**Comment by shmilylty** [comment]
Q:使用Excel打开结果的csv中有中文乱码，怎么解决？

A:由于Excel打开文件需要带BOM头识别编码，而默认生成的结果csv文件是UTF-8编码不是UTF-8-BOM，所以会使用Excel打开会出现中文乱码，有以下解决办法：

1.在一开始运行OneForAll，设置format参数为xls或者xlsx格式。

2.使用NotePad++类似工具转化编码格式为UTF-8-BOM。

3.使用Excel软件导入结果csv文件中的数据。

**Comment by 321811788** [comment]
强！管用！

**Comment by mangodmai** [comment]
Does not support xls format 怎麼不行呢, xlsx也一樣

**Comment by shmilylty** [comment]
> Does not support xls format 怎麼不行呢, xlsx也一樣

现在不支持xls和xlsx格式导出了

**Comment by huafenga** [comment]
在Excel里面改一下编码就可以了：https://jingyan.baidu.com/article/4dc408484776fbc8d846f168.html

**Comment by shmilylty** [comment]
使用最新仓库代码可解决此问题
