### ISSUE TITLE
一运行电脑就断网

### ISSUE THREAD

**Issue by UIWP0** [shmilylty/OneForAll#223]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
是

**Bug描述**
清晰而简洁的Bug描述（必写）
跑到 brute 模块时电脑无线就坏了，甚至都搜不到无线，只有重启才能解决，拿个模块好像叫 massdns 啥的

**运行环境**
 - 系统：[例如Windows 10 x64]（必写）
 - Python版本：[例如3.7.1]（必写）
 - OneForAll版本：[例如0.3.0]（必写）
 - win10 64   虚拟机 kali 64
 - Python 3.9.7
 - onforall 0.4..3
 
**如何复现**
复现步骤（选写）
python3 onforall.py  target  run

复现命令（必写）

**报错文本**
复制完整的报错文本（必写）

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）
![image](https://user-images.githubusercontent.com/32759429/133877824-324948aa-8dc2-4c37-b29c-3f583cd8be39.png)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by je5442804** [comment]
给家人们整无语了，这也算BUG？你自己都很清楚哪里有问题了, config/setting.py里面调一下爆破并发速度

**Comment by JrDw0** [comment]
Close the issue because this is not a bug.
