### ISSUE TITLE
This result object does not return rows. It has been closed automatically    导入结果时报错

### ISSUE THREAD

**Issue by ckzhongck** [shmilylty/OneForAll#226]
13:50:27,923 [ERROR] database:40 - ('This result object does not return rows. It has been closed automatically.',)
13:50:27,923 [INFOR] brute:496 - Finished Brute module to brute 3itm.net
13:50:27,923 [ERROR] database:40 - ('This result object does not return rows. It has been closed automatically.',)
13:50:27,923 [ERROR] database:40 - ('This result object does not return rows. It has been closed automatically.',)
13:50:27,939 [ERROR] database:40 - ('This result object does not return rows. It has been closed automatically.',)
13:50:27,939 [INFOR] resolve:142 - Start resolving subdomains of 3itm.net
13:50:27,939 [INFOR] resolve:60 - Saving resolved results
13:50:27,939 [ERROR] database:40 - ('This result object does not return rows. It has been closed automatically.',)
13:50:27,939 [ERROR] database:40 - ('This result object does not return rows. It has been closed automatically.',)
0it [00:00, ?it/s]:40 - ('This result object does not return rows. It has been closed automatically.',)
13:50:27,939 [INFOR] request:258 - Start requesting subdomains of 3itm.net
13:50:27,939 [INFOR] request:39 - Port range:[80, 443]
Request Progress: 1it [00:00, ?it/s]]
request:56 - Generating request urls
Request Progress: 1it [00:00, ?it/s] -
Requesting urls in bulk
13:50:27,955 [ERROR] database:40 - ('This result object does not return rows. It has been closed automatically.',)

**Comment by foozzi** [comment]
same problem
