### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by indigo-sadland** [shmilylty/OneForAll#229]
**Whether the latest code is used**
Yes

**Bug description**
Running OneForAll from Parallesl Desktop virtual environment results in _Fatal Python error: Segmentation fault_

**Operation environment**
 - Host System information: MacBook Air (M1) MacOS Monterey 12.0.1
 - Virtual Environment: Parallels Desktop Ubuntu 20.0.4 (aarch64)
 - Python version: 3.10
 - OneForAll version: 0.4.3
 
**How to reproduce**
1. Step (optional)

2. Command 
python3 oneforall.py --target uber.com --brute False run

**Error text**
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**FaultHandler Output**
[log.txt](https://github.com/shmilylty/OneForAll/files/7482735/log.txt)

**Comment by shmilylty** [comment]
oneforall不支持aarch64架构的系统
