### ISSUE TITLE
censys_api.py代码有误

### ISSUE THREAD

**Issue by jiangsir404** [shmilylty/OneForAll#23]
**是否使用了最新代码**
是

**Bug描述**
1. 后一个post请求的数据data是第一个post请求的结果，参数误用了，导致后面的请求发不出去。
2. fields字段最好再加上parsed.names字段，因为子域名主要在parsed.names字段中，会比只获取parsed.subject_dn的结果更多。

**如何复现**
do("360.cn")

**预期结果**
测试可以获取到400个子域名

**实际结果**
实际只获取了39个子域名,后面的请求都没发成功。

**屏幕截图**
![image](https://user-images.githubusercontent.com/17962401/65686076-1d221580-e096-11e9-9c8a-792647a2dac7.png)

**运行环境**
 - 系统：Windows 10 x64
 - Python版本：3.7.1
- OneForAll版本：0.0.6

**报错文本**
{'status': 'error', 'error_type': 'malformed_request', 'error': 'request is missing the required field query'}

**Comment by shmilylty** [comment]
感谢反馈，已经解决这个问题了。
