### ISSUE TITLE
This result object does not return rows. It has been closed automatically

### ISSUE THREAD

**Issue by foozzi** [shmilylty/OneForAll#231]
similar problem but no solution - https://github.com/shmilylty/OneForAll/issues/226

**Comment by foozzi** [comment]
problem with `google-api-python-client` and `uritemplate`
if you update these modules, the problem will appear

**Comment by shmilylty** [comment]
python3 -m pip uninstall sqlalchemy 
python3 -m pip install sqlalchemy==1.3.22
