### ISSUE TITLE
oneforall调用YandexSearch，GoogleQuery，HackerTargetQuery， YahooSearch报错

### ISSUE THREAD

**Issue by w990222** [shmilylty/OneForAll#240]
![image](https://user-images.githubusercontent.com/33209022/143726878-58790751-3677-46b9-a411-7e0b1d20368d.png)
系统有代理
![image](https://user-images.githubusercontent.com/33209022/143726893-f7280ab9-6402-46f4-80af-1c56d211fba3.png)

**Comment by jhhd88** [comment]
代理被这几个站封了，换个IP
