### ISSUE TITLE
zoomeye 模块API请求地址改变

### ISSUE THREAD

**Issue by jhhd88** [shmilylty/OneForAll#244]
![image](https://user-images.githubusercontent.com/15847202/150497001-77ec75d9-e657-48a2-86f4-77e5f1752d21.png)

web改成了domain,以及请求参数也改变了

**Comment by jhhd88** [comment]
![image](https://user-images.githubusercontent.com/15847202/150499048-6d3cdab0-8cba-4e35-bea6-2ee61899c22c.png)

**Comment by ThestaRY7** [comment]
我想你可能是误会了，

https://www.zoomeye.org/doc#web-search

zommeye_api.py 文件里写了，用zoomeye的hostname语法去检索的。
你提到的/domain/search 只是另一种用法。

或许是使用hostname语法去检索能比/domain/search发现更多资产

**Comment by shmilylty** [comment]
已修改为更准确的/domain/search接口
