### ISSUE TITLE
Expects only one row when using RecordCollection.one

### ISSUE THREAD

**Issue by lwzSoviet** [shmilylty/OneForAll#254]
OneForAll\common\records.py", line 238, in one

    raise ValueError('RecordCollection contained more than one row. '

ValueError: RecordCollection contained more than one row. Expects only one row when using RecordCollection.one

**Comment by ju1ceju1ce** [comment]
我也出现了相同的问题，师傅知道该怎么解决么

**Comment by ko2sec** [comment]
same here.

**Comment by ysyyrps123** [comment]
oneforall can't grab fofa‘s result as if i used apikey and email?
