### ISSUE TITLE
想请教一个问题

### ISSUE THREAD

**Issue by m0rning0o0** [shmilylty/OneForAll#255]
师傅你好，最近在学习这个项目的源码，但是离线数据集那里有一些疑惑，想请教一个问题：
data 目录下的 [ip2location.zip](https://github.com/shmilylty/OneForAll/blob/master/data/ip2location.zip) 和 [authoritative_dns.txt](https://github.com/shmilylty/OneForAll/blob/master/data/authoritative_dns.txt) 这两个文件的数据来源是哪里？

**Comment by shmilylty** [comment]
[ip2location.zip](https://github.com/shmilylty/OneForAll/blob/master/data/ip2location.zip)是从https://www.ip2location.com/下载的
