### ISSUE TITLE
0.44新版urllib3==1.26.5导致fofa api访问超时

### ISSUE THREAD

**Issue by jhhd88** [shmilylty/OneForAll#264]
两个版本已分别测试相同的5个域名。
降回urllib3==1.26.4以后正常

**Comment by shmilylty** [comment]
已更改为urllib3==1.26.9 师傅再试一下呢

**Comment by jhhd88** [comment]
> 已更改为urllib3==1.26.9 师傅再试一下呢

这个版本可以
