### ISSUE TITLE
在用大端口收集之后就卡死不动了

### ISSUE THREAD

**Issue by gusechuisheng** [shmilylty/OneForAll#267]
**是否使用了最新代码**
是

**Bug描述**
在用大端口收集之后就卡死不动了

Request Progress:   0%|                        | 3/7728 [00:00<04:17, 29.96it/s]Start requesting subdomains of 
Request Progress:   0%|                        | 6/7728 [00:00<04:22, 29.47it/s] [INFOR] request:39 - Port range:[80, 81, 280, 300, 443, 591, 593, 832, 888, 901, 981, 1010, 1080, 1100, 1241, 1311, 1352, 1434, 1521, 1527, 1582, 1583, 1944, 2082, 2082, 2086, 2087, 2095, 2096, 2222, 2301, 2480, 3000, 3128, 3333, 4000, 4001, 4002, 4100, 4125, 4243, 4443, 4444, 4567, 4711, 4712, 4848, 4849, 4993, 5000, 5104, 5108, 5432, 5555, 5800, 5801, 5802, 5984, 5985, 5986, 6082, 6225, 6346, 6347, 6443, 6480, 6543, 6789, 7000, 7001, 7002, 7396, 7474, 7674, 7675, 7777, 7778, 8000, 8001, 8002, 8003, 8004, 8005, 8006, 8008, 8009, 8010, 8014, 8042, 8069, 8075, 8080, 8081, 8083, 8088, 8090, 8091, 8092, 8093, 8016, 8118, 8123, 8172, 8181, 8200, 8222, 8243, 8280, 8281, 8333, 8384, 8403, 8443, 8500, 8530, 8531, 8800, 8806, 8834, 8880, 8887, 8888, 8910, 8983, 8989, 8990, 8991, 9000, 9043, 9060, 9080, 9090, 9091, 9200, 9294, 9295, 9443, 9444, 9800, 9981, 9988, 9990, 9999, 10000, 10880, 11371, 12043, 12046, 12443, 15672, 16225, 16080, 18091, 18092, 20000, 20720, 24465, 28017, 28080, 30821, 43Request Progress:   0%|                       | 13/7728 [00:00<02:42, 47.58it/s]
Request Progress:   0%|                       | 23/7728 [00:00<03:31, 36.52it/s]Generating request urls
Request Progress:   0%|                       | 37/7728 [00:01<03:46, 33.96it/s]request:217 - Requesting urls in bulk
Request Progress: 7729it [03:15, 20.80it/s]                                     09:57:19,649 [INFOR] request:264 - Found that****** has 733 alive subdomains
Request Progress: 7729it [04:06, 31.32it/s]

然后下面就卡死了，一直不动

**Comment by shmilylty** [comment]
请求这块后续要再优化一下 建议优先使用小端口吧

**Comment by gusechuisheng** [comment]
> 请求这块后续要再优化一下 建议优先使用小端口吧

好滴，谢谢师傅

**Comment by gusechuisheng** [comment]
> 请求这块后续要再优化一下 建议优先使用小端口吧

那这个large端口可以在哪修改吗，我去修改一下啊

**Comment by shmilylty** [comment]
可以使用small

**Comment by shmilylty** [comment]
修改默认端口泛微看这里https://github.com/shmilylty/OneForAll/blob/master/config/default.py#L145

**Comment by gusechuisheng** [comment]
日志是这样的，是检查cdn，然后卡了一个小时多
2022-07-11 09:56:46,497 [DEBUG] MainProcess(35428):RequestThread-786 (18704) | request.get_resp:137 - (MaxRetryError("HTTPConnectionPool(host='hire2047.********', port=1521): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001FA8604B070>, 'Connection to hire2047.faas.********** timed out. (connect timeout=13)'))"),)
2022-07-11 09:57:19,649 [INFOR] MainProcess(35428):MainThread        (28252) | request.run_request:264 - Found that ****** has 733 alive subdomains
2022-07-11 09:57:48,384 [DEBUG] MainProcess(35428):MainThread        (28252) | iscdn.do_check:67 - Checking cdn

**Comment by shmilylty** [comment]
@gusechuisheng 这个问题已经修复 可以再测试一下

**Comment by JrDw0** [comment]
长时间未更新，先关闭
