### ISSUE TITLE
请填写BUG标题扫描结果csv文件中的中文内容乱码

### ISSUE THREAD

**Issue by UIWP0** [shmilylty/OneForAll#270]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
是
**Bug描述**
清晰而简洁的Bug描述（必写）
批量扫描域名，结果csv文档中的中文乱码
![image](https://user-images.githubusercontent.com/32759429/179693010-e071825d-bd56-4f7b-b7c0-3b2c190f3370.png)

**运行环境**
 - 系统：Kali
 - Python3.9
 - OneForAll 0.4.5
 

**如何复现**

复现命令
python3 Oneforall.py --targets url.txt run
**报错文本**
复制完整的报错文本（必写）
![image](https://user-images.githubusercontent.com/32759429/179693346-23e55e9f-2640-4e8a-8d61-05d2c35c2637.png)

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by shmilylty** [comment]
参考#22
