### ISSUE TITLE
API配置问题

### ISSUE THREAD

**Issue by ybdt** [shmilylty/OneForAll#271]
疑问：
看到api.py和default.py中都可以配置api，对于同一个配置，两个文件中配置一个就可以吧？
![image](https://user-images.githubusercontent.com/65813455/180620177-09a7f28b-57d8-4a31-b081-0c9b7624de96.png)

建议：
发现有的api配置（hunter）default.py中有，api.py中没有，建议将api配置统一到一个文件中

**Comment by shmilylty** [comment]
配置api.py就行了，default.py是为了防止api.py没有对应字段引发异常报错。

**Comment by ybdt** [comment]
so ga

发自我的iPhone
