### ISSUE TITLE
是否可以支持三级及以下域名探测

### ISSUE THREAD

**Issue by Quickass** [shmilylty/OneForAll#272]
我在个人测试过程中，发现了二级子域，但是三级子域挂载不同的服务内容，是否可以支持深入探测

**Comment by u21h2** [comment]
试下在data/public_suffix_list.dat添加上你的二级域名

**Comment by shmilylty** [comment]
OneForAll在收集子域时会默认收集层级的子域，爆破功能也支持三级以下域名探测。
