### ISSUE TITLE
报错，百度无解

### ISSUE THREAD

**Issue by HWHDusk** [shmilylty/OneForAll#273]
![image](https://user-images.githubusercontent.com/87553336/181470633-5c8cb4b6-10b7-4c4d-9ce2-ae8227566818.png)
![image](https://user-images.githubusercontent.com/87553336/181470774-e68c24ff-80e6-4202-8051-ba15ac407cc3.png)
可以说下是什么原因吗，麻烦大家了

**Comment by shmilylty** [comment]
下载最新版本

**Comment by allanprince** [comment]
国外的那个站挂了，所以网络环境检查过不去

**Comment by HWHDusk** [comment]
> 

还是不行
![image](https://user-images.githubusercontent.com/87553336/183595263-e27e72cb-b674-4468-b0f2-c57c23eeb21e.png)
![image](https://user-images.githubusercontent.com/87553336/183595298-10c2abee-aa9e-49e9-9aa4-8d7d87393f99.png)
![image](https://user-images.githubusercontent.com/87553336/183595346-a80f5aa4-1779-4962-907b-ea86c058252c.png)

**Comment by allanprince** [comment]
> > 
> 
> 还是不行 ![image](https://user-images.githubusercontent.com/87553336/183595263-e27e72cb-b674-4468-b0f2-c57c23eeb21e.png) ![image](https://user-images.githubusercontent.com/87553336/183595298-10c2abee-aa9e-49e9-9aa4-8d7d87393f99.png) ![image](https://user-images.githubusercontent.com/87553336/183595346-a80f5aa4-1779-4962-907b-ea86c058252c.png)

你先访问http://ip-api.com/json/看能不能打开，不行的话就得挂代理用才行，或者可以自己调，看我的最新提交的bug

**Comment by HWHDusk** [comment]
> > > 
> > 
> > 
> > 还是不行 ![image](https://user-images.githubusercontent.com/87553336/183595263-e27e72cb-b674-4468-b0f2-c57c23eeb21e.png) ![image](https://user-images.githubusercontent.com/87553336/183595298-10c2abee-aa9e-49e9-9aa4-8d7d87393f99.png) ![image](https://user-images.githubusercontent.com/87553336/183595346-a80f5aa4-1779-4962-907b-ea86c058252c.png)
> 
> 你先访问[http://ip-api.com/json/看能不能打开，不行的话就得挂代理用才行，或者可以自己调，看我的最新提交的bug](http://ip-api.com/json/%E7%9C%8B%E8%83%BD%E4%B8%8D%E8%83%BD%E6%89%93%E5%BC%80%EF%BC%8C%E4%B8%8D%E8%A1%8C%E7%9A%84%E8%AF%9D%E5%B0%B1%E5%BE%97%E6%8C%82%E4%BB%A3%E7%90%86%E7%94%A8%E6%89%8D%E8%A1%8C%EF%BC%8C%E6%88%96%E8%80%85%E5%8F%AF%E4%BB%A5%E8%87%AA%E5%B7%B1%E8%B0%83%EF%BC%8C%E7%9C%8B%E6%88%91%E7%9A%84%E6%9C%80%E6%96%B0%E6%8F%90%E4%BA%A4%E7%9A%84bug)

打不开，

**Comment by allanprince** [comment]
> > > > 
> > > 
> > > 
> > > 还是不行 ![image](https://user-images.githubusercontent.com/87553336/183595263-e27e72cb-b674-4468-b0f2-c57c23eeb21e.png) ![image](https://user-images.githubusercontent.com/87553336/183595298-10c2abee-aa9e-49e9-9aa4-8d7d87393f99.png) ![image](https://user-images.githubusercontent.com/87553336/183595346-a80f5aa4-1779-4962-907b-ea86c058252c.png)
> > 
> > 
> > 你先访问[http://ip-api.com/json/看能不能打开，不行的话就得挂代理用才行，或者可以自己调，看我的最新提交的bug](http://ip-api.com/json/%E7%9C%8B%E8%83%BD%E4%B8%8D%E8%83%BD%E6%89%93%E5%BC%80%EF%BC%8C%E4%B8%8D%E8%A1%8C%E7%9A%84%E8%AF%9D%E5%B0%B1%E5%BE%97%E6%8C%82%E4%BB%A3%E7%90%86%E7%94%A8%E6%89%8D%E8%A1%8C%EF%BC%8C%E6%88%96%E8%80%85%E5%8F%AF%E4%BB%A5%E8%87%AA%E5%B7%B1%E8%B0%83%EF%BC%8C%E7%9C%8B%E6%88%91%E7%9A%84%E6%9C%80%E6%96%B0%E6%8F%90%E4%BA%A4%E7%9A%84bug)
> 
> 打不开，

所以这个才是源头，看那个报错就是因为没结果导致的

**Comment by jhhd88** [comment]
\OneForAll\common\utils.py 第499行

**Comment by HWHDusk** [comment]
> \OneForAll\common\utils.py 第499行 修改为[https://ipinfo.io/json或者https://speed.cloudflare.com/meta](https://ipinfo.io/json%E6%88%96%E8%80%85https://speed.cloudflare.com/meta) ![image](https://user-images.githubusercontent.com/15847202/183597540-db6d37a5-b5d7-4bef-b5db-9ea7f56dc2b8.png)

![image](https://user-images.githubusercontent.com/87553336/183599106-9a738fc1-a9de-4d42-96da-990ec3da8806.png)
![image](https://user-images.githubusercontent.com/87553336/183599147-61d3c679-d44b-4d6d-a43f-ddaffe56e474.png)
![image](https://user-images.githubusercontent.com/87553336/183599181-4032ad09-6d20-4fcc-86ae-a2e736435e1f.png)
谢谢大佬，这个可以访问，但是问题还是

**Comment by HWHDusk** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 还是不行 ![image](https://user-images.githubusercontent.com/87553336/183595263-e27e72cb-b674-4468-b0f2-c57c23eeb21e.png) ![image](https://user-images.githubusercontent.com/87553336/183595298-10c2abee-aa9e-49e9-9aa4-8d7d87393f99.png) ![image](https://user-images.githubusercontent.com/87553336/183595346-a80f5aa4-1779-4962-907b-ea86c058252c.png)
> > > 
> > > 
> > > 你先访问[http://ip-api.com/json/看能不能打开，不行的话就得挂代理用才行，或者可以自己调，看我的最新提交的bug](http://ip-api.com/json/%E7%9C%8B%E8%83%BD%E4%B8%8D%E8%83%BD%E6%89%93%E5%BC%80%EF%BC%8C%E4%B8%8D%E8%A1%8C%E7%9A%84%E8%AF%9D%E5%B0%B1%E5%BE%97%E6%8C%82%E4%BB%A3%E7%90%86%E7%94%A8%E6%89%8D%E8%A1%8C%EF%BC%8C%E6%88%96%E8%80%85%E5%8F%AF%E4%BB%A5%E8%87%AA%E5%B7%B1%E8%B0%83%EF%BC%8C%E7%9C%8B%E6%88%91%E7%9A%84%E6%9C%80%E6%96%B0%E6%8F%90%E4%BA%A4%E7%9A%84bug)
> > 
> > 
> > 打不开，
> 
> 所以这个才是源头，看那个报错就是因为没结果导致的

嗯嗯，改了个可以访问的。还是报错

**Comment by jhhd88** [comment]
更新到最新版，然后把原来的results文件夹全删掉

**Comment by shmilylty** [comment]
此问题已解决，请使用最新仓库代码。
