### ISSUE TITLE
API配置问题

### ISSUE THREAD

**Issue by zlgxzswjy** [shmilylty/OneForAll#278]
**是否使用了最新代码**
是

**Bug描述**
api.py和default.py中的api接口支持不一致，比如hunter fullhunt在default.py中有，在api.py中没有。
请问师傅在api.py中没有的接口是否能够使用呢？如果可以使用的话，是直接填在default.py中，还是可以在api.py里新建字段进行填写呢

**Comment by shmilylty** [comment]
OneForAll默认是先从api.py读取配置，如果在api.py里没有的配置则会从default.py寻找配置，所以你可以在api.py里新建字段进行填写。
