### ISSUE TITLE
while running disconnecting my router.

### ISSUE THREAD

**Issue by Walidhossain010** [shmilylty/OneForAll#281]
while running disconnecting my router. probably due to masscan. any way to limit masscan?
<img width="565" alt="Screenshot 2022-09-28 at 10 48 00 PM" src="https://user-images.githubusercontent.com/32749515/192841993-ede619c2-83c7-42f8-9725-0f12bcf49cdf.png">

**Comment by shmilylty** [comment]
You can set the brute_concurrent_num parameter to a smaller number https://github.com/shmilylty/OneForAll/blob/master/config/setting.py#L38
