### ISSUE TITLE
Http连接问题

### ISSUE THREAD

**Issue by haonny** [shmilylty/OneForAll#282]
使用时发现，一直在报HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5a98109b40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
  显示爬虫的时候网络不可达，请问有没有师傅改过这里，本人代码能力不好，网上查到的解决方案怕改坏了

**Comment by shmilylty** [comment]
需要配置翻墙代理

**Comment by haonny** [comment]
> 需要配置翻墙代理

我在配置文件里配置了代理了，是不是dns解析的问题呢

**Comment by shmilylty** [comment]
你配置的内容是啥
