### ISSUE TITLE
经常卡死在那什么情况

### ISSUE THREAD

**Issue by ASDWQad** [shmilylty/OneForAll#283]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
是
**Bug描述**
清晰而简洁的Bug描述（必写）
14:17:28,545 [INFOR] module:63 - Sitemap模块耗时90.3秒发现子域0个
卡在这里就不动了

**运行环境**
 - 系统：Windows 11 x64
 - Python版本：3.6
 - OneForAll版本：0.4.5
 
**如何复现**
复现步骤（选写）
python oneforall.py --valid=0 --req=False --target= run

复现命令（必写）
python oneforall.py --valid=0 --req=False --target= run

**报错文本**
复制完整的报错文本（必写）

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by shmilylty** [comment]
可以把超时时间设置短一点
