### ISSUE TITLE
使用github模块时出现验证邮件：github Please verify your device

### ISSUE THREAD

**Issue by yida223** [shmilylty/OneForAll#29]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下）
否
**Bug描述**
清晰而简洁的Bug描述
使用github模块时出现验证邮件：github Please verify your device
**如何复现**
复现步骤（可不写）
复现命令
在config.py中补充github模块
![image](https://user-images.githubusercontent.com/42206940/67739871-d8035180-fa4e-11e9-9cea-c9aa178505d0.png)

**预期结果**
清晰而简洁的预期结果描述（可不写）
脚本运行时出现验证邮件
**实际结果**
清晰而简洁的实际结果描述（如出现什么错误）
导致github模块无法使用
**屏幕截图**
![image](https://user-images.githubusercontent.com/42206940/67739871-d8035180-fa4e-11e9-9cea-c9aa178505d0.png)

![image](https://user-images.githubusercontent.com/42206940/67739795-9c688780-fa4e-11e9-9e30-168c54b9fc9e.png)

**运行环境**
 - 系统：centos7.5 腾讯云[例如Windows 10 x64]
 - Python版本：3.7.0 [例如3.7.1]
- OneForAll版本：0.0.7 [例如0.0.6]

**报错文本**
复制完整的报错文本
无

**Comment by shmilylty** [comment]
这个应该就是一个Github为了确认生成Token操作发的验证吧

**Comment by shmilylty** [comment]
暂时关闭，有问题可以继续沟通。
