### ISSUE TITLE
bug csv export

### ISSUE THREAD

**Issue by gearcapitan** [shmilylty/OneForAll#290]
**Whether the latest code is used**
Yes 

**Bug description**
export fail to csv 

**Operation environment**
 - System information: last kali linux december 2022
 - Python version: [e.g. 3.7.1] last
 - OneForAll version: [e.g. 0.3.0] last
 
**How to reproduce**
1. Step (optional)
![imagen](https://user-images.githubusercontent.com/13740942/209618597-bcd52968-35c2-40c0-8b9d-1b902121f8da.png)

2. Command (required)
python3 oneforall.py --target domain.com run
**Error text**

**Comment by JrDw0** [comment]
We need more log to fix. If you still need help, reopen the issue.
