### ISSUE TITLE
ImportError: cannot import name 'sre_parse' from 're'

### ISSUE THREAD

**Issue by clcc2019** [shmilylty/OneForAll#295]
**Whether the latest code is used**
Yes
**Bug description**
```bash
Traceback (most recent call last):
  File "/root/workdir/domain/OneForAll/oneforall.py", line 16, in <module>
    from brute import Brute
  File "/root/workdir/domain/OneForAll/brute.py", line 14, in <module>
    import exrex
  File "/usr/local/lib/python3.11/dist-packages/exrex.py", line 25, in <module>
    from re import sre_parse, U
ImportError: cannot import name 'sre_parse' from 're' (/usr/lib/python3.11/re/__init__.py)
```

**Operation environment**
 - System information: debian11
 - Python version: python3
 - OneForAll version: latest
 
**How to reproduce**
1. Step (optional)
install and run python3 oneforall.py --help

2. Command (required)
python3 oneforall.py --help

**Error text**
Copy the complete error text (required)

**Expected results**
A clear and concise description of the expected results (optional, such as what a normal situation should look like)

**Actual results**
A clear and concise description of the actual results (optional, such as any errors)

**Screenshot**
Screenshot of complete OneForAll execution process (recommended upload)

**Log upload**
Upload oneforall.log files (it is recommended to upload logs in case of complex problems)

**Supplementary information**
Some other supplementary notes about bug

**Comment by clcc2019** [comment]
edit /usr/local/lib/python3.11/dist-packages/exrex.py
```python
#from re import sre_parse, U
import sre_parse

**Comment by Markusklarcus1** [comment]
Getting the same error while on mac, tried doing what clcc2019 said but cant find the file to do it in.

**Comment by Guymosciski** [comment]
> Getting the same error while on mac, tried doing what clcc2019 said but cant find the file to do it in.

you check your python version such as 
python3 -V 
then you will get a version number now replace the python3.1.1 in below command as your version whichever it is try check
nano /usr/local/lib/python3.11/dist-packages/exrex.py
then comment the line like this
#from re import sre_parse, U 
add the line
import sre_parse
ctrl+x 
enter 
try python3 oneforall.py --help
q
