### ISSUE TITLE
结果文件为空

### ISSUE THREAD

**Issue by Ludovicofu** [shmilylty/OneForAll#296]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
否
**Bug描述**
清晰而简洁的Bug描述（必写）
运行完后的csv格式文件和json格式文件结果均为空
**运行环境**
 - 系统：Windows 10 x64
 - Python版本：3.9
 - OneForAll版本：OneForAll-0.4.5
 
**如何复现**
复现步骤（选写）

复现命令（必写）
python oneforall.py --target 域名 run -f json
**报错文本**
复制完整的报错文本（必写）
15:17:55,978 [ERROR] database:40 - ('This result object does not return rows. It has been closed automatically.',)
15:17:55,997 [ERROR] database:40 - ('This result object does not return rows. It has been closed automatically.',)
![image](https://user-images.githubusercontent.com/91811209/215694739-de9c4c4d-b14d-4f42-9f67-81020584dd30.png)
![image](https://user-images.githubusercontent.com/91811209/215694817-e5abaea1-a7f7-4b02-98d5-f458cbe55b0e.png)

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by JrDw0** [comment]
看起来是你的网络环境有问题，没有得到正常结果。可以换个网络再试一下，先关闭，如果有问题再打开issue。
