### ISSUE TITLE
windows运行无法使用颜色模块

### ISSUE THREAD

**Issue by sv3nbeast** [shmilylty/OneForAll#30]
from colorama import init
init(autoreset=True)

onforall.py加入此导入，可使windows下的python输出的颜色正常，不在乱码

![_P(T0TPNW6_$D )~8X2B)V9](https://user-images.githubusercontent.com/55974091/68918000-81647a00-07a7-11ea-9bb1-17f8c8055126.png)

**Comment by shmilylty** [comment]
谢谢反馈，不过init(autoreset=True)中autorest这个参数貌似是指每次打印结束时自动重置终端颜色为终端默认颜色。https://github.com/tartley/colorama#init-keyword-args

**Comment by shmilylty** [comment]
暂时关闭，有问题可以继续沟通。
