### ISSUE TITLE
请问怎么加快爆破速度？

### ISSUE THREAD

**Issue by zglaozhu** [shmilylty/OneForAll#32]
我用aiobrute.py进行爆破 百万字典  一个晚上只能爆破进度到5%左右
配置如下
# 爆破时使用的进程数(根据系统中CPU数量情况设置 不宜大于CPU数量 默认为系统中的CPU数量)
brute_process_num = os.cpu_count()
brute_coroutine_num = 1000  # 爆破时每个进程下的协程数(不宜大于1000)
# 爆破所使用的字典路径 默认data/subdomains.txt
brute_wordlist_path = data_storage_path.joinpath('subnames.txt')
brute_task_segment = 50000

请问怎么才能加快爆破速度呢？

**Comment by hiw0rld** [comment]
同问 +1  

爆破确实有点慢，调这个参数也无效

**Comment by shmilylty** [comment]
更新再测试一下呢，之前有一个存在更改config.py中参数无效的问题。
