### ISSUE TITLE
config.py 中协程数和字典划分对aiobrute.py  无效

### ISSUE THREAD

**Issue by zglaozhu** [shmilylty/OneForAll#33]
**是否使用了最新代码**
是

**Bug描述**
config.py 中协程数和字典划分对aiobrute.py  无效

**如何复现**
复现步骤（可不写）
复现命令
py -3 aiobrute.py --target alimama.com --wordlist subdomains.txt   --format txt --path 2.txt run
**预期结果**
清晰而简洁的预期结果描述（可不写）
预期对aiobrute.py 有效
**实际结果**
config.py 中协程数和字典划分对aiobrute.py  无效

**屏幕截图**

**运行环境**
 - 系统：win10
 - Python版本：3.7 因为3.8  pip 安装包老出错  所以用3.7 运行
- OneForAll版本：当前最新版本

**报错文本**

# 爆破时使用的进程数(根据系统中CPU数量情况设置 不宜大于CPU数量 默认为系统中的CPU数量)
brute_process_num = os.cpu_count()
brute_coroutine_num = 256  # 爆破时每个进程下的协程数(不宜大于500)
# 爆破所使用的字典路径 默认data/subdomains.txt
brute_wordlist_path = data_storage_path.joinpath('subnames.txt')
brute_task_segment = 50000

py -3 aiobrute.py --target alimama.com --wordlist subdomains.txt   --format txt --path 2.txt run
11:14:52,847 [INFOR] utils:128 - 获取到1个域名
11:14:52,878 [INFOR] aiobrute:286 - 开始执行AIOBrute模块爆破域名alimama.com
11:14:52,879 [INFOR] aiobrute:287 - 使用4进程乘64协程
11:14:52,881 [INFOR] aiobrute:41 - 正在探测alimama.com是否使用泛解析
11:14:52,937 [ALERT] aiobrute:55 - alimama.com使用了泛解析
11:14:52,940 [ALERT] aiobrute:56 - 01c19ea0.alimama.com 解析到域名: 01c19ea0.alimama.com. IP: {'223.82.248.117'} TTL: 60
11:14:52,943 [INFOR] aiobrute:210 - 使用subdomains.txt字典
Progress:   0%| | 0/1553 [00:00<?, ?it/s]aiobrute:129 - 爆破字典大小：776251
11:14:54,121 [INFOR] aiobrute:255 - 正在爆破alimama.com的域名
Progress:   0%| | 5/1553 [05:42<4:58:29, 11.57s/it]

**Comment by shmilylty** [comment]
谢谢反馈，已经修复。https://github.com/shmilylty/OneForAll/commit/5cd71ca6e728e6f0cbe509895520feb7e4b045ca
