### ISSUE TITLE
请填写BUG标题

### ISSUE THREAD

**Issue by zhizhi-2** [shmilylty/OneForAll#335]
**是否使用了最新代码**
是

**Bug描述**
利用证书透明度收集子域中的这个censys_api文件运行会显示这个错误
https://search.censys.io/api/v1/search/certificates 404 - Not Found 34302

**运行环境**
 - 系统：win11
 - Python版本：3.9
 - OneForAll版本：最新的
 
**如何复现**
我是下载源码，直接运行收集模块中利用证书透明度收集里的censys_api.py这个文件

**报错文本**
16:39:11,239 [ALERT] utils:273 - POST https://search.censys.io/api/v1/search/certificates 404 - Not Found 34302
16:39:11,241 [INFOR] module:64 - CensysAPIQuery module took 1.9 seconds found 0 subdomains

**预期结果**
应该能查询到子域名把，试了好几个域名都是0个

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**其他补充**
关于bug的其他一些补充说明

**Comment by JrDw0** [comment]
应该是因为Censys的API更新了使用策略，一个账号只能使用60天了。

> The 60-day API access limit is now in affect. Your account no longer has access to the API.
