### ISSUE TITLE
duckduckgo python错误

### ISSUE THREAD

**Issue by hiw0rld** [shmilylty/OneForAll#34]
**是否使用了最新代码**
是

**Bug描述**
默认跑  duckduckgo 报错 19:29:20,608 [ERROR] duckduckgo:45 - list index out of range

**如何复现**
应该是列表容错错误

**预期结果**
连接错误/0域名/多数域名

**实际结果**
列表错误

**屏幕截图**

**运行环境**
 - 系统：mac
 - Python版本：3.7.3]
- OneForAll版本：latest

**Comment by shmilylty** [comment]
目前没有搞懂duckduckgo搜索参数的变化规律，希望有表哥可以一起研究和反馈一下。实在不行的话我就移除duckduckgo模块，这个模块收集结果对整体结果影响不大。

**Comment by shmilylty** [comment]
暂时移除了duckduckgo模块
