### ISSUE TITLE
请填写BUG标题

### ISSUE THREAD

**Issue by chenpaowuyifan** [shmilylty/OneForAll#341]
是否使用最新代码** 是或否（如果不是，请尝试克隆最新代码并重新运行！）**错误描述**

**错误描述*** 简洁明了的错误描述（必须填写）

**运行环境** - 系统：[例如 Windows 10 x64]（必须写） - Python 版本：[例如 3.7.1]（必须编写） - OneForAll 版本：[例如 0.3.0] （必须编写）
 
**如何重现** 重现步骤（可选）

复制命令（必须写）

**错误文本** 复制完整的错误文本（必填）

预期结果** 对预期结果的简明扼要的描述（可选，例如正常情况下应该如何） **实际结果** 对实际结果的简明扼要的描述（可选，例如正常情况下应该如何

**实际结果*** 对实际结果的简明扼要描述（可选，例如发生了什么错误）

**截图*** 完整 OneForAll 执行过程的截图（建议上传）

**上传日志*** 上传 oneforall.log 日志文件（建议用于复杂问题）

**其他补充内容*** 有关错误的其他补充内容

**Comment by JrDw0** [comment]
未提供问题及日志，先关闭
