### ISSUE TITLE
sqlite3数据库太占空间

### ISSUE THREAD

**Issue by hbdxmz** [shmilylty/OneForAll#356]
oneforall的sqlite3数据库文件很大，这个数据库文件可以使用配置文件选择是否生成吗？
 跑10个域名，这个sqlite3快到90G了，盘快要没了。。
<img width="638" alt="ed5c02174256b2e0cbfde0c45c0b8b3" src="https://github.com/shmilylty/OneForAll/assets/94107024/29cdc85e-0c94-4f0e-a0ce-075c26a69e51">

**Comment by JrDw0** [comment]
不行，解析的历史记录依赖于数据库，但是如果用不上历史记录相关的功能可以每次跑完自己手动删除一下数据库
