### ISSUE TITLE
某些域名结果不兼容导致程序报错

### ISSUE THREAD

**Issue by liuyusjs** [shmilylty/OneForAll#36]
**Describe the bug**
如alipay.com

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shmilylty** [comment]
大佬更新再试试呢。

**Comment by liuyusjs** [comment]
alipay.com

Traceback (most recent call last):
  File "oneforall.py", line 199, in <module>
    fire.Fire(OneForAll)
  File "C:\Python3\Python37\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Python3\Python37\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "C:\Python3\Python37\lib\site-packages\fire\core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "oneforall.py", line 192, in run
    self.main()
  File "oneforall.py", line 161, in main
    self.data = loop.run_until_complete(task)
  File "C:\Python3\Python37\lib\asyncio\base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "C:\Python3\Python37\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Python3\Python37\lib\asyncio\base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Python3\Python37\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Python3\Python37\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
ValueError: too many file descriptors in select()

可能是有些多值得情况没有考虑，今天更新的版本好像导出结果也有点问题，，

大佬可以测试一下批量

100tal.com
163.com
360.cn
alibaba.com
alipay.com
baidu.com
bilibili.com
bugx.io
butian.net
bytedance.com
cainiao.com
creditease.cn
ctrip.com
dianrong.com
douyu.com
dvpnet.io
ele.me
focuschina.com
fuiou.com
guazi.com
huawei.com
immomo.com
iqiyi.com
kuaishou.com
le.com
lexinfintech.com
ly.com
meituan.com
mobike.com
netease
oppo.com
pingan.com
qq.com
qunar.com
rong360.com
safedog.cn
seebug.org
sf-express.com
sina.com.cn
sogou.com
sohu
tecent
tencent
tutorabc.com.cn
vip.com
vipkid.com.cn
vivo.com.cn
vulbox.com
wacai.com
wanmei.com
webank.com
weibo.com
wifi.com
xiaomi
yirendai.com
zto.com


语句：
python3 oneforall.py --target list.txt --format json run

可以发现很多程序的问题哦

**Comment by liuyusjs** [comment]
前面的问题应该是多并发导致的报错

**Comment by liuyusjs** [comment]
E://111111111111111111-old/oneforall/oneforall.py", line 161, in main
    self.data = loop.run_until_complete(task)E://111111111111111111-old/oneforall/oneforall.py", line 161, in main
    self.data = loop.run_until_complete(task)

**Comment by liuyusjs** [comment]
跟了一下，是因为asyncio异步请求，因为asyncio内部用到了select，而select就是那个什么系统打开文件数是有限度的，上面的代码一次性将处理url的函数作为任务扔进了一个超大的List中，这就引起了错误，抛出了异常，这样的话子域名的数量一但过多就会抛出异常，
![image](https://user-images.githubusercontent.com/38901459/71705264-b4c39c80-2e19-11ea-8969-a7866ae6b25c.png)

**Comment by liuyusjs** [comment]
![image](https://user-images.githubusercontent.com/38901459/71706615-11768580-2e21-11ea-90b5-fe794b18d943.png)

**Comment by liuyusjs** [comment]
![image](https://user-images.githubusercontent.com/38901459/71706858-1e47a900-2e22-11ea-8a0a-945f990339c0.png)
新版的似乎也存在该问题，

**Comment by shmilylty** [comment]
请使用Python3.8，不要使用Python3.7，因为Python3.7默认使用SelectorEventLoop，Python3.8默认使ProactorEventLoop。
