### ISSUE TITLE
导出结果无法判断是否为新子域

### ISSUE THREAD

**Issue by LuckyC4t** [shmilylty/OneForAll#38]
**是否使用了最新代码**
是

**Bug描述**
在--req=False的情况下，最终结果中new字段和其他字段为None

**如何复现**
复现命令
python3.8 oneforall.py --target example.com --show=True --format=json --req=False --dns=True run
**预期结果**
![image](https://user-images.githubusercontent.com/40694340/71765332-3efd2500-2f2e-11ea-822f-92d58c1b9ace.png)

**实际结果**
![image](https://user-images.githubusercontent.com/40694340/71765336-53412200-2f2e-11ea-9ae9-f6b8ca4a2d7c.png)

**运行环境**
 - 系统：Ubuntu 18.04 x64
 - Python版本：3.8.0
- OneForAll版本：v0.0.8#dev

**报错文本**
无

**Comment by shmilylty** [comment]
已解决，请使用最新代码。
