### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by aaeolus** [shmilylty/OneForAll#4]
我用的mac系统，装pycares出现问题，网上找了一圈没有解决好，只有windows系统上的

 fatal error: too many errors emitted, stopping now [-ferror-limit=]
  20 errors generated.
  error: command 'clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pycares
  Running setup.py clean for pycares
Failed to build pycares
Installing collected packages: pycares
  Running setup.py install for pycares ... error

**Comment by shmilylty** [comment]
这个问题之前有表哥遇到了，现在有两个方法可以解决：
1.[pycares](https://github.com/saghul/pycares)首页说明了，pycares是基于c-ares这个C库开发的，但是c-ares这个库不支持TTL，然后pycares向c-ares添加支持TTL的补丁，但是c-ares愿意合并，所以pycares就自带了带了补丁的c-ares，所以解决办法就是通过brew卸载自带c-ares，https://github.com/saghul/pycares/issues/93，然后重新安装pycares依赖，这个方法也有表哥测试能行。

2.升级系统版本到最新的10.14.6，经过测试最新版本macOS安装pycares依赖都没有问题。

**Comment by aaeolus** [comment]
感谢精灵表哥答疑

**Comment by jackie-oaknorth** [comment]
最新的系統10.14.6還是有這個問題， python 3.7.4

**Comment by shmilylty** [comment]
@jackie-oaknorth 使用方法1

**Comment by shellfeel** [comment]
brew 卸载c-cares 权限不够，要关闭sip，好折腾，有表哥有更好的解决方案没😭
