### ISSUE TITLE
Suggestion about crt.sh

### ISSUE THREAD

**Issue by attacker34** [shmilylty/OneForAll#41]
There is need to add some prefix keywords too while searching on crt.sh for specific domain.

Like if we see simple domain without using any prefix on crt.sh

```
https://crt.sh/?q=%25.yahoo.com

```

But what if we use prefixes like  

```
api,Internal,Staging,Stag,Production,Product,dev,devs,prod,new

```

We will get different results from above.

```
https://crt.sh/?q=%25.api.yahoo.com

```

Please add prefixes in the tool to grab more subdomains related to a domain.

**Comment by shmilylty** [comment]
Is there a way to get all the subdomains at once?

**Comment by attacker34** [comment]
@shmilylty No.... You've to search each and every possible search box whether its Github or Bing , crt.sh etc

**Comment by shmilylty** [comment]
There is no good solution now, so turn off issue for the time being.
