### ISSUE TITLE
Tutorial Please

### ISSUE THREAD

**Issue by jepunband** [shmilylty/OneForAll#43]
**Is your feature request related to a problem? Please describe.**
Can you please do a tutorial on the subdomain scanner and takeover. I'm trying to use this tool
but i'm not sure what is going on...

i have used tool like Sublist3r to enum the sub-domains.

but how to get your tool to enum domains and check for the vulnerability to take over the sub-domain?

thanks.

**Comment by shmilylty** [comment]
--takeover=True
