### ISSUE TITLE
ValueError: too many file descriptors in select()

### ISSUE THREAD

**Issue by c0d1007** [shmilylty/OneForAll#52]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
是最新代码
**Bug描述**
生成结果错误

**运行环境**
 - 系统：[例如Windows 10 x64]（必写）
win10x64
 - Python版本：[例如3.7.1]（必写）
python3.7.4
 - OneForAll版本：[例如0.0.6]（必写）
 
**如何复现**
复现步骤（选写）
直接运行命令
复现命令（必写）
python3 oneforall.py --target domian run
**报错文本**
Request Progress:  80%|██████████████████▍    | 531/664 [00:09<00:02, 64.68it/s]ValueError: to
o many file descriptors in select()
**预期结果**
正常结果不太清楚，应该是正常生成文件把

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）
![image](https://user-images.githubusercontent.com/43197505/75599676-1e8eb880-5ae2-11ea-8280-dceb199f406c.png)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**Comment by shmilylty** [comment]
请使用Python 3.8.0以上版本
