### ISSUE TITLE
建议在保存结果的时候再进行一些数据处理

### ISSUE THREAD

**Issue by coco413** [shmilylty/OneForAll#56]
- 1、dns解析后的部分结果结尾存在点号，虽然正常但可能会影响到域名拼接URL、端口，requests访问是正常的，但浏览器访问http://zy.gov.cn.:8080这样格式还是有些不兼容。
- 2、建议增加一个配置信息，是否允许发现关联域名，比如在扫baidu.com域名的时候会存在shifen.com域名，这时候根域名变了但还是百度的不影响，不过也会有误扫比如在扫政府域名时候出现了sanshua.cn根域。

**Comment by shmilylty** [comment]
感谢，第一个建议会采纳，第二次建议还没有想好，暂时不做。
