### ISSUE TITLE
Fofa api调用时出现500错误

### ISSUE THREAD

**Issue by helloyw** [shmilylty/OneForAll#58]
**是否使用了最新代码**
是
**Bug描述**

Fofa api调用时出现500错误  Internal Server Error 8049

**运行环境**
 - 系统：[例如Windows 10 x64]（必写）
 - Python版本：[例如3.7.1]（必写）
 - OneForAll版本：[例如0.0.6]（必写）
 
**如何复现**
复现步骤（选写）
复现命令（必写）

**报错文本**
Internal Server Error 8049

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**Comment by shmilylty** [comment]
有没有运行截图呢

**Comment by helloyw** [comment]
![QQ图片20200321191846](https://user-images.githubusercontent.com/32027872/77225310-dfb3c600-6ba8-11ea-9c6c-8ebb5dadcab1.png)

**Comment by shmilylty** [comment]
你使用浏览器访问看看呢

**Comment by helloyw** [comment]
同样也是500报错

**Comment by shmilylty** [comment]
那应该是fofa的服务器出问题了

**Comment by helloyw** [comment]
好的谢谢!

**Comment by jhhd88** [comment]
不是服务器的问题，是你的key要重置一下，你是不是多人在使用？换下key就好了。
