### ISSUE TITLE
oneforall无法正常退出

### ISSUE THREAD

**Issue by ody5sey** [shmilylty/OneForAll#59]
**是否使用了最新代码**
是

**Bug描述**
oneforall还是无法正常退出

**运行环境**
 - 系统：[例如macOS]（必写）
 - Python版本：[例如3.8.2]（必写）
 - OneForAll版本：[例如0.1.0]（必写）
 
**如何复现**

`if __name__ == '__main__':
    # fire.Fire(OneForAll)
    OneForAll('example.cn').run()
    # OneForAll('./domains.txt').run()`

**报错文本**
无法退出

**预期结果**
正常退出

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**Comment by shmilylty** [comment]
正在debug

**Comment by shmilylty** [comment]
已经解决
