### ISSUE TITLE
--valid 1 参数输出问题

### ISSUE THREAD

**Issue by 0xzer0** [shmilylty/OneForAll#68]
**是否使用了最新代码**
是（{v0.1.0#dev}）

**Bug描述**
在使用 --valid 1 导出有效子域时，导出结果为 --valid  None 的全部结果。

**运行环境**
 - 系统：kali 64
 - Python版本：3.8.2
 - OneForAll版本：0.1.0
 
**如何复现**
复现步骤（选写）

复现命令（必写）
python3 oneforall.py --target xxxx.com --valid 1 --port small --format json --path /root/test/xxxx.com.json run

**报错文本**
无

**预期结果**
使用 --valid 1 导出的子域应仅包含 valid=1 的结果

**实际结果**
使用 --valid 1 导出的子域仍包含 valid=0 的结果

**Comment by shmilylty** [comment]
现在应该解决了这个问题，你再测试一下呢。

**Comment by 0xzer0** [comment]
问题依然存在，json结果中"valid"全部为 null，csv结果中"valid"仍有0和1；另外在指定路径的情况下，在默认路径下也会生成结果文件。 @shmilylty

**Comment by 0xzer0** [comment]
> 现在应该解决了这个问题，你再测试一下呢。@ 0xzer0

问题依然存在，json结果中“ valid”全部为null，csv结果中“ valid”仍为0和1；另外在指定路径的情况下，在各种路径下也会生成结果文件。@shmilylty

**Comment by 0xzer0** [comment]
> 现在应该解决了这个问题，你再测试一下呢。@0xzer0

问题依然存在，json结果中“ valid”全部为 null，csv结果中仍有“valid”为0的结果；另外在指定路径的情况下，在默认路径下也会生成结果文件。@shmilylty

**Comment by shmilylty** [comment]
@0xzer0 注意一下现在之前的valid参数已经改为alive，而现在的valid只是用来表示爆破过程中发现的有效子域个数，如果没有开启爆破那默认值就为null。

**Comment by 0xzer0** [comment]
> @0xzer0 注意一下现在之前的valid参数已经改为alive，而现在的valid只是用来表示爆破过程中发现的有效子域个数，如果没有开启爆破那默认值就为null。

命令：python3 oneforall.py --target xxx.com --alive True --port small --format json --path /root/test/xxx.com.json run
问题：在默认路径下输出预期的存活结果，在指定路径下输出全部结果

**Comment by shmilylty** [comment]
是的，现在是这样设计的。

**Comment by shmilylty** [comment]
已解决
