### ISSUE TITLE
运行异常结束

### ISSUE THREAD

**Issue by thinks520** [shmilylty/OneForAll#70]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
是
**Bug描述**
清晰而简洁的Bug描述（必写）
massdns结束直接 "killed"，未能生成结果
**运行环境**
 - 系统：[例如Windows 10 x64]（必写）ubuntu18
 - Python版本：[例如3.7.1]（必写）python3.8.2
 - OneForAll版本：[例如0.0.6]（必写）git pull 之后最新版
 
**如何复现**
复现步骤（选写）

复现命令（必写）
python3.8 oneforall.py --target test.com --brute True run
**报错文本**
复制完整的报错文本（必写）
17:45:42,661 [INFOR] brute:568 - 结束执行massdns
Killed

**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**Comment by shmilylty** [comment]
这个应该是内存不足导致的，正在优化内存中。

**Comment by shmilylty** [comment]
已经解决

**Comment by thinks520** [comment]
你好，前几天更新后，大概8月4号左右，继续出现类似问题。
11:43:57,879 [INFOR] resolve:186 - Running massdns to resolve subdomains
11:43:59,350 [INFOR] resolve:70 - Processing resolved results
Killed

**Comment by thinks520** [comment]
python3.8 oneforall.py --target test.com --brute True --port large run

**Comment by thinks520** [comment]
目前git pull 到最新版仍然有此问题，不确定是不是我机器内存（只有1G）过小问题。

**Comment by shmilylty** [comment]
> 目前git pull 到最新版仍然有此问题，不确定是不是我机器内存（只有1G）过小问题。

现在的生成的文件较小了，更新一下代码再试试呢。

**Comment by thinks520** [comment]
可能也是个人服务器原因。换了台性能好点的服务器，用最新版的代码就没问题了，感谢作者大佬耐心解答。
