### ISSUE TITLE
MaxRetryError

### ISSUE THREAD

**Issue by websecer** [shmilylty/OneForAll#72]
17:11:56,979 [ERROR] module:118 - (MaxRetryError("HTTPSConnectionPool(host='api.certspotter.com', port=443): Max retries exceeded with url: /v1/issuances?domain=orps.cn&include_subdomains=true&expand=dns_names (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f048408d1d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
17:11:56,980 [INFOR] module:65 - CertSpotterQuery模块耗时6.0秒发现子域0个
17:11:56,983 [ERROR] module:118 - (MaxRetryError("HTTPSConnectionPool(host='transparencyreport.google.com', port=443): Max retries exceeded with url: /transparencyreport/api/v3/httpsreport/ct/certsearch?include_expired=true&include_subdomains=true&domain=orps.cn (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f048417c160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
17:11:56,984 [INFOR] module:65 - GoogleQuery模块耗时6.0秒发现子域0个
17:11:56,985 [ERROR] module:118 - (MaxRetryError("HTTPSConnectionPool(host='ctsearch.entrust.com', port=443): Max retries exceeded with url: /api/v1/certificates?fields=subjectDN&domain=orps.cn&includeExpired=true (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f048406cb00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
17:11:56,985 [INFOR] module:65 - EntrustQuery模块耗时6.0秒发现子域0个
17:11:56,987 [ERROR] module:118 - (MaxRetryError("HTTPSConnectionPool(host='crt.sh', port=443): Max retries exceeded with url: /?q=%25.orps.cn&output=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f048406c780>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
17:11:56,988 [INFOR] module:65 - CrtshQuery模块耗时6.0秒发现子域0个
17:11:56,991 [ERROR] module:146 - (MaxRetryError("HTTPSConnectionPool(host='www.censys.io', port=443): Max retries exceeded with url: /api/v1/search/certificates (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f048408ea58>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
17:11:56,991 [INFOR] module:65 - CensysAPIQuery模块耗时6.0秒发现子域0个
17:11:56,999 [INFOR] module:65 - CertInfo模块耗时6.0秒发现子域0个
17:11:57,000 [ERROR] module:118 - (MaxRetryError("HTTPConnectionPool(host='orps.cn', port=80): Max retries exceeded with url: /crossdomain.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f048403bba8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
17:11:57,001 [INFOR] module:65 - CrossDomainXml模块耗时6.0秒发现子域0个
17:11:57,007 [ERROR] module:118 - (MaxRetryError("HTTPConnectionPool(host='orps.cn', port=80): Max retries exceeded with url: /robots.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f048408e390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
17:11:57,007 [INFOR] module:65 - Robots模块耗时6.0秒发现子域0个
17:11:57,011 [ERROR] module:118 - (MaxRetryError("HTTPConnectionPool(host='orps.cn', port=80): Max retries exceeded with url: /sitemap.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f048402d208>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
17:11:57,011 [INFOR] module:65 - Sitemap模块耗时6.0秒发现子域0个
17:11:57,015 [ERROR] module:118 - (MaxRetryError("HTTPConnectionPool(host='orps.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0484040358>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
17:11:57,027 [ERROR] module:118 - (MaxRetryError("HTTPSConnectionPool(host='dnsdumpster.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0484040400>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
17:11:57,027 [INFOR] module:65 - DNSdumpsterQuery模块耗时6.0秒发现子域0个
17:11:57,031 [ERROR] threatcrowd:25 - (MaxRetryError("HTTPSConnectionPool(host='www.threatcrowd.org', port=443): Max retries exceeded with url: /searchApi/v2/domain/report?domain=orps.cn (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f048402d710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
17:11:57,031 [INFOR] module:65 - ThreatCrowdQuery模块耗时6.0秒发现子域0个
17:11:57,035 [ERROR] module:118 - (MaxRetryError("HTTPConnectionPool(host='ptrarchive.com', port=80): Max retries exceeded with url: /tools/search4.htm?label=orps.cn&date=ALL (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f046041edd8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
17:11:57,035 [INFOR] module:65 - PTRArchiveQuery模块耗时6.0秒发现子域0个
17:11:57,039 [ERROR] module:146 - (MaxRetryError("HTTPConnectionPool(host='sbd.ximcx.cn', port=80): Max retries exceeded with url: /DomainServlet (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f04604213c8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)
17:11:57,039 [INFOR] module:65 - XimcxQuery模块耗时6.0秒发现子域0个
17:11:57,047 [ERROR] module:118 - (MaxRetryError("HTTPSConnectionPool(host='alexa.chinaz.com', port=443): Max retries exceeded with url: /orps.cn (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0460409860>: Failed to establish a new connection: [Errno -3] Temporary failure in name res

**Comment by shmilylty** [comment]
主机不能访问外网，已解决。
