### ISSUE TITLE
无有效解析结果

### ISSUE THREAD

**Issue by jhhd88** [shmilylty/OneForAll#74]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
是
**Bug描述**
清晰而简洁的Bug描述（必写）
跑任何域名到了massdns阶段都会显示无有效解析结果，然后停止了。
**运行环境**
 - 系统：[例如Windows 10 x64]（必写）
 - Python版本：[例如3.7.1]（必写）
 - OneForAll版本：[例如0.0.6]（必写）
 Windows 10 x64
Python 3.8
0.2
**如何复现**
复现步骤（选写）

复现命令（必写）
oneforall.py --target 任何域名 run
**报错文本**
复制完整的报错文本（必写）
15:11:00,147 [INFOR] utils:557 - 结束执行massdns
15:11:00,147 [INFOR] brute:312 - 正在统计IP次数
15:11:00,154 [INFOR] brute:340 - 正在处理解析结果
15:11:00,171 [FATAL] brute:365 - 无有效解析结果
**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）
在更新前都没有问题
**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）
![image](https://user-images.githubusercontent.com/15847202/80458071-d6193d00-8962-11ea-97b6-09f1831ca5e8.png)

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**Comment by shmilylty** [comment]
https://github.com/shmilylty/OneForAll/commit/99af838fcb94355b8e138cb838a1061c77fe3b42
已解决
