### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by websecer** [shmilylty/OneForAll#75]
05:50:18,391 [INFOR] utils:560 - 执行命令 E:\Myprofile\Soft\Scan Tool\OneForAll\oneforall\thirdparty\massdns\windows\x64\massdns_wind
ows_amd64.exe  --status-format ansi --processes 1 --socket-count 1 --hashmap-size 1000 --resolvers E:\Myprofile\Soft\Scan Tool\OneForAll\oneforall\data\cn_nameservers.txt --resolve-count 50 --type A --flush --output J --outfile E:\Myprofile\Soft\Scan Tool\OneForAll\oneforall\results\temp\resolved_result_baidu.com_20200430_055016.json --error-log E:\Myprofile\Soft\Scan Tool\OneForAll\oneforall\results\massdns.log E:\Myprofile\Soft\Scan Tool\OneForAll\oneforall\results\temp\generated_subdomains_baidu.com_20200430_055016.txt
'E:\Myprofile\Soft\Scan' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
05:50:18,428Traceback (most recent call last):
 [  File "oneforall.py", line 250, in <module>
INFOR    ] fire.Fire(OneForAll)utils
:  File "D:\install\python38\lib\site-packages\fire\core.py", line 138, in Fire
562 -     component_trace = _Fire(component, args, parsed_flag_args, context, name)结束执行massdns

  File "D:\install\python38\lib\site-packages\fire\core.py", line 463, in _Fire
05:50:18,429     [component, remaining_args = _CallAndUpdateTrace(INFOR
]   File "D:\install\python38\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
brute:    312component = fn(*varargs, **kwargs) -
  File "oneforall.py", line 237, in run
正在统计IP次数
    self.main()
  File "oneforall.py", line 181, in main
    brute.run()
  File "E:\Myprofile\Soft\Scan Tool\OneForAll\oneforall\brute.py", line 604, in run
    valid_subdomains = self.main(self.domain)
  File "E:\Myprofile\Soft\Scan Tool\OneForAll\oneforall\brute.py", line 580, in main
    ip_times = stat_ip_times(output_path)
  File "E:\Myprofile\Soft\Scan Tool\OneForAll\oneforall\brute.py", line 314, in stat_ip_times
    with open(result_path) as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Myprofile\\Soft\\Scan Tool\\OneForAll\\oneforall\\results\\temp\\resolved_result_baidu.com_20200430_055016.json'

E:\Myprofile\Soft\Scan Tool\OneForAll\oneforall (master -> origin)

**Comment by shmilylty** [comment]
E:\Myprofile\Soft\Scan Tool\OneForAll\ 路径中有空格

**Comment by websecer** [comment]
感谢
