### ISSUE TITLE
Domain Name Being Appended with n<domainname>

### ISSUE THREAD

**Issue by merlin-ke** [shmilylty/OneForAll#77]
**Describe the bug**

**To Reproduce**
 i ran the python oneforall.py --target example.com run command

**Expected behavior**
A csv list with correct domains

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Kali rolling 5.3.0-kali3-amd64 #1 SMP Debian 5.3.15-1kali1 (2019-12-09) x86_64 GNU/Linux
Python 3.7.5
 - Browser: N/A
 - Version N/A

**Smartphone (please complete the following information):**

**Additional context**
After the scan has finished, i noticed some urls were being appended with an n and some garbled with incomplete sub domain names.
eg https://nhub.example.com, 
a correct sub-domain can be hub.example.com  but the csv will have ub.example.com

Great tool though. I was able to nab some subdomain that other tools havent been managed to get.

**Comment by kenjoe41** [comment]
Was coming on here to make this issue.
I suppose it is in the regex of the [util.py](https://github.com/shmilylty/OneForAll/blob/master/oneforall/common/utils.py). Would be better to check for the `\n` character in the json and skip it.

**Comment by shmilylty** [comment]
I don't know how to reproduce this problem. Can you say it in more detail? For example, what is the domain name tested, it's better to have a diagram to explain it. @merlin-ke

**Comment by eur0pa** [comment]
@shmilylty 

```
oneforall.log:{'mta-sts.forwarding.hackerone.com', 'api.hackerone.com', 'www.hackerone.com', 'links.hackerone.com', 'docs.hackerone.com', 'hackerone.com', 'nwww.hackerone.com', 'mta-sts.hackerone.com', 'mta-sts.managed.hackerone.com', 'support.hackerone.com', 'go.hackerone.com', 'ninfo.hackerone.com'}```

`nwww` and `ninfo` are not valid subdomains. Something somewhere is stripping `\n<subdomain>` (as in newline) to `n<subdomain>`

**Comment by merlin-ke** [comment]
> I don't know how to reproduce this problem. Can you say it in more detail? For example, what is the domain name tested, it's better to have a diagram to explain it. @merlin-ke

**Comment by merlin-ke** [comment]
sorry for the late reply but @eur0pa already mentioned it. Thanks @eur0pa
