### ISSUE TITLE
Clean Output fed to other tools

### ISSUE THREAD

**Issue by attacker007** [shmilylty/OneForAll#81]
Hi @Tardis07 

Tool is really amazing and I wanna pipe the results into another tools like Sn1per etc for further testing of subdomains. It will be very cool feature if tool can somehow give clean output which can be feed to other tools .

Thanks.

**Comment by shmilylty** [comment]
This feature is now implemented
https://github.com/shmilylty/OneForAll/commit/0e3584d9068d8b699c493382e480f52fb4e25fda
