### ISSUE TITLE
spyse的api调用貌似变了

### ISSUE THREAD

**Issue by xxnbyy** [shmilylty/OneForAll#82]
已经从v1变成了v2，而且方式有改变。
![image](https://user-images.githubusercontent.com/20261647/81483250-4bdcad00-926f-11ea-8d81-fa3b08db3420.png)
![image](https://user-images.githubusercontent.com/20261647/81483254-4f703400-926f-11ea-9c15-bd874ded2f50.png)

**Comment by shmilylty** [comment]
已解决
