### ISSUE TITLE
配置了riskiq的api但是未生效

### ISSUE THREAD

**Issue by xxnbyy** [shmilylty/OneForAll#83]
已经配置了图中位置的API，但是运行时未生效，原因未知
![image](https://user-images.githubusercontent.com/20261647/81483289-b8f04280-926f-11ea-9dfe-3f3416bbd98b.png)
![image](https://user-images.githubusercontent.com/20261647/81483307-cefe0300-926f-11ea-8d85-3ee0ec2f85d4.png)

**Comment by shmilylty** [comment]
你确认你已经正确在api.py里填写了passivedns_api_token吗

**Comment by xxnbyy** [comment]
看错了-。-
