### ISSUE TITLE
ImportError: cannot import name 'setting' from 'config'

### ISSUE THREAD

**Issue by ipk1** [shmilylty/OneForAll#87]
when i run the command i get 

 python3 oneforall.py --target example.com run
Traceback (most recent call last):
  File "oneforall.py", line 15, in <module>
    import dbexport
  File "/root/Tools/OneForAll/dbexport.py", line 13, in <module>
    from common import utils
  File "/root/Tools/OneForAll/common/utils.py", line 18, in <module>
    from common.domain import Domain
  File "/root/Tools/OneForAll/common/domain.py", line 3, in <module>
    from config import setting
ImportError: cannot import name 'setting' from 'config' (/usr/local/lib/python3.8/dist-packages/config/__init__.py)

installed dependencies also

**Comment by shmilylty** [comment]
Because you installed the config library, which caused a conflict with the config directory, the solution is to uninstall the config library, `pip3 uninstall config`.@ipk1

**Comment by ipk1** [comment]
thanks that sorted it out

**Comment by anuoplus** [comment]
wa!thank you very much,so it is!

> Because you installed the config library, which caused a conflict with the config directory, the solution is to uninstall the config library, `pip3 uninstall config`.[@ipk1](https://github.com/ipk1)
