### ISSUE TITLE
Add some api search

### ISSUE THREAD

**Issue by tom0li** [shmilylty/OneForAll#9]
Alexa  http://alexa.chinaz.com/
Googlect   https://transparencyreport.google.com/https/certificates
Ilink  
PassiveDNS  http://ptrarchive.com/
Pgpsearch  http://pgp.mit.edu/pks/lookup?search=baidu.com&op=index
ThreatCrowd   https://www.threatcrowd.org/searchApi/v2/domain/report/?domain=baidu.com

**Comment by tom0li** [comment]
可以把teemo的一些接口整合一下   https://github.com/bit4woo/teemo

**Comment by shmilylty** [comment]
谢谢反馈，你上面提到的接口目前都已经有了，你可以到看一下[收集模块说明](https://github.com/shmilylty/OneForAll/blob/master/docs/collection_modules.md)里面已经实现的接口，另外Pgpsearch这个接口是一个邮箱账号收集接口，在写OneForAll之前已经看过目前大部分已开源的子域收集项目包括teemo，如果还有其他比较好的接口欢迎反馈。
