### ISSUE TITLE
ModuleNotFoundError: No module named 'modules.collect'; 'modules' is not a package

### ISSUE THREAD

**Issue by myhunt1996** [shmilylty/OneForAll#94]
![Screenshot from 2020-05-15 18-51-57](https://user-images.githubusercontent.com/62182034/82054737-0855c900-96dd-11ea-84c2-9a359f1bde8f.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shmilylty** [comment]
Try to clone the latest code and run it again
