### ISSUE TITLE
result.sqlite3 的内容问题

### ISSUE THREAD

**Issue by thinks520** [shmilylty/OneForAll#96]
**是否使用了最新代码**
是或否（如果不是的话尝试克隆最新的代码再跑一下！）
是
**Bug描述**
清晰而简洁的Bug描述（必写）
你好，有个问题试了很多次，result.sqlite3 的内容里，所有行数的title和banner一直都为空，其它字段的内容是正常的，查看了all*.csv是有banner和title的，sqlite3里面的就没有，是最新不支持sqlite还是有什么新改动吗
**运行环境**
 - 系统：[例如Windows 10 x64]（必写）
 - Python版本：[例如3.7.1]（必写）
 - OneForAll版本：[例如0.0.6]（必写）
 Ubuntu16  python3.8  git pull最新版
**如何复现**
复现步骤（选写）

复现命令（必写）

**报错文本**
复制完整的报错文本（必写）
没有报错
**预期结果**
清晰而简洁的预期结果描述（选写，如正常情况应该是怎么样的）

**实际结果**
清晰而简洁的实际结果描述（选写，如出现什么错误）

**屏幕截图**
完整OneForAll执行流程截图（建议上传）

**日志上传**
上传oneforall.log日志文件（复杂问题建议上传）

**Comment by shmilylty** [comment]
感觉不太会有这种情况出现，怎么能复现一下？

**Comment by thinks520** [comment]
已解决，个人调用参数问题，使用了--dns Flase参数， 理解以为只是不反查IP，没想到导致端口扫描和title,banner失效
