### ISSUE TITLE
解析的时候显示DNS超时

### ISSUE THREAD

**Issue by freekey000** [shmilylty/OneForAll#97]
请问不断的显示DNS超时该怎么处理呢？之前使用到没有出现这个问题

16:07:09,997 [ALERT] brute:35 - DNS resolve timeout, retrying
16:07:40,008 [ALERT] brute:35 - DNS resolve timeout, retrying

--- Logging error in Loguru Handler #2 ---
Record was: None
Traceback (most recent call last):
dns.exception.Timeout: The DNS operation timed out after 30.004562377929688 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
tenacity.TryAgain

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
tenacity.RetryError: RetryError[<Future at 0x7f7349d19a00 state=finished raised TryAgain>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
TypeError: cannot pickle '_thread.RLock' object
--- End of logging error ---

**Comment by shmilylty** [comment]
克隆最新OneForAll再试试，这个可能是当时网络的问题。

**Comment by SingleH** [comment]
克隆最新的，换了几个网，还是这样（本机Windows），

**Comment by SingleH** [comment]
> 
> 
> 克隆最新OneForAll再试试，这个可能是当时网络的问题。

克隆最新的，换了几个网，还是这样（本机Windows）

**Comment by cwkiller** [comment]
同样遇到这个问题，新加坡机器没被墙linux

**Comment by shmilylty** [comment]
@cwkiller @freekey000 @Corgizz 最新的代码还存在这个问题吗 具体复现命令是啥？

**Comment by Corgizz** [comment]
目前没出现过了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jing Ling"<notifications@github.com&gt;; 
发送时间: 2020年9月3日(星期四) 晚上9:11
收件人: "shmilylty/OneForAll"<OneForAll@noreply.github.com&gt;; 
抄送: "十八"<812358080@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [shmilylty/OneForAll] 解析的时候显示DNS超时 (#97)





 
@cwkiller @freekey000 @Corgizz 最新的代码还存在这个问题吗 具体复现命令是啥？
