### ISSUE TITLE
add This 

### ISSUE THREAD

**Issue by Fawadkhanfk** [shmilylty/OneForAll#98]
https://github.com/allyomalley/LiveTargetsFinder

Try to Add This Script So the result wiill me more accurate

**Comment by shmilylty** [comment]
Can you explain it in more detail? I'm not sure what you need.

**Comment by Fawadkhanfk** [comment]
its just a simple script use for the live domains like it just the dad domain and give the clean list of domain the resolved ones\

**Comment by shmilylty** [comment]
The output of OneForAll already has a field of whether it is alive or not.
